package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * HyAssist generated by hbm2java
 */
@Entity
@Table(name = "hy_assist")
@SequenceGenerator(name = "sequenceGenerator", sequenceName = "hy_assist_sequence")
public class Assist implements java.io.Serializable {

	private Long id;
	private String requiredSupport;
	private String application;
	private Integer assistType;
	private Date starttime;
	private Date endtime;
	private BigDecimal cost;
	private String phone;
	private HyAdmin proposer;
	private Store store;
	private HyAdmin operator;
	private Integer status;
	private Date createDate;
	private Date modifyDate;
	public static final int legalType=1;
	public static final int storeType=0;
	public static final int taxType=2;

	public Assist() {
	}

	public Assist(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="store")
	public Store getStore() {
		return store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "required_support")
	public String getRequiredSupport() {
		return this.requiredSupport;
	}

	public void setRequiredSupport(String requiredSupport) {
		this.requiredSupport = requiredSupport;
	}

	@Column(name = "application")
	public String getApplication() {
		return this.application;
	}

	public void setApplication(String application) {
		this.application = application;
	}

	@Column(name = "assist_type")
	public Integer getAssistType() {
		return this.assistType;
	}

	public void setAssistType(Integer assistType) {
		this.assistType = assistType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starttime", length = 19)
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endtime", length = 19)
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "cost", precision = 10)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="proposer")
	public HyAdmin getProposer() {
		return proposer;
	}

	public void setProposer(HyAdmin proposer) {
		this.proposer = proposer;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="operator")
	public HyAdmin getOperator() {
		return operator;
	}

	public void setOperator(HyAdmin operator) {
		this.operator = operator;
	}

	@PrePersist
	public void prePersist(){
		this.setCreateDate(new Date());
		this.setStatus(0);
	}
	@PreUpdate
	public void preUpdate(){
		this.setModifyDate(new Date());
	}
}
