package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * BankList generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "hy_bank_list")
public class BankList implements java.io.Serializable {
	public enum BankType {
		bank,
		alipay,
		wechatpay,
		onlinebank,
		businessBank,
	}

	public enum Yinhangleixing {
		/**
		 * 采购部供应商
		 **/
		cgbgys,
		/**
		 * 总部财务
		 **/
		zbcw,
		/**
		 * 分公司银行账号
		 **/
		fengongsi,
		/**
		 * 直营门店增值业务供应商银行帐号
		 **/
		valueAddedSupplier
	}
	private Long id;
	private HyCompany hyCompany;
	
	/** 银行类型 银行 支付宝 微信支付之类*/
	private BankType type;
	
	/** 开户人名称 */	
	private String accountName;
	
	/** 开户行名称 */
	private String bankName;
	
	/** 银行联行号 */
	private String bankCode;
	
	/** 对公是false 对私是true */
	private Boolean bankType;
	
	/** 银行账号 */
	private String bankAccount;
	
	/** 简称 */
	private String alias;

	/** 状态 0:删除 1:正常*/
	private Integer bankListStatus;
	
	/** 银行账号的类型 */
	private Yinhangleixing yhlx;

	public BankList(){
		
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}


	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company")
	public HyCompany getHyCompany() {
		return this.hyCompany;
	}

	public void setHyCompany(HyCompany hyCompany) {
		this.hyCompany = hyCompany;
	}
	@Column(name = "type")
	public BankType getType() {
		return type;
	}

	public void setType(BankType type) {
		this.type = type;
	}

	@Column(name = "account_name")
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "bank_name")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_code")
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "bank_type")
	public Boolean getBankType() {
		return this.bankType;
	}

	public void setBankType(Boolean bankType) {
		this.bankType = bankType;
	}

	@Column(name = "bank_account", nullable = false)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "alias")
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}
	public Yinhangleixing getYhlx() {
		return yhlx;
	}
	public void setYhlx(Yinhangleixing yhlx) {
		this.yhlx = yhlx;
	}

	@Column(name = "bank_list_status")
	public Integer getBankListStatus() {
		return bankListStatus;
	}

	public void setBankListStatus(Integer bankListStatus) {
		this.bankListStatus = bankListStatus;
	}

	@PrePersist
	public void prePersist() {
		if(this.alias==null) {
		    if(this.type == BankType.bank){
                this.alias = this.bankName+"(尾号"+this.bankAccount.substring(bankAccount.length()-4, bankAccount.length())+")";
            }else if(this.type == BankType.alipay){
		        this.alias = "支付宝-" + this.bankAccount;
            }else if(this.type == BankType.wechatpay){
                this.alias = "微信支付-" + this.bankAccount;
            }
		}
		if(this.bankListStatus == null){
			this.bankListStatus = 1;
		}
	}
}
