package com.hongyu.entity;
// default package
// Generated 2018-2-8 15:07:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyBusinessOrderDepot generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"
})
@Table(name = "hy_business_order_depot")
public class BusinessOrderDepot implements java.io.Serializable {

	private Long id;
	private BusinessOrderItem orderitemId;
	private Inbound inboundId;
	private String depotCode;
	private Integer outboundQuantity;
	private Date outboundTime;
	private HyAdmin operator;
	private Integer returnQuantity;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderitem_id")
	public BusinessOrderItem getOrderitemId() {
		return this.orderitemId;
	}

	public void setOrderitemId(BusinessOrderItem orderitemId) {
		this.orderitemId = orderitemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inbound_id")
	public Inbound getInboundId() {
		return this.inboundId;
	}

	public void setInboundId(Inbound inboundId) {
		this.inboundId = inboundId;
	}

	@Column(name = "depot_code")
	public String getDepotCode() {
		return this.depotCode;
	}

	public void setDepotCode(String depotCode) {
		this.depotCode = depotCode;
	}

	@Column(name = "outbound_quantity")
	public Integer getOutboundQuantity() {
		return this.outboundQuantity;
	}

	public void setOutboundQuantity(Integer outboundQuantity) {
		this.outboundQuantity = outboundQuantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "outbound_time", length = 19)
	public Date getOutboundTime() {
		return this.outboundTime;
	}

	public void setOutboundTime(Date outboundTime) {
		this.outboundTime = outboundTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operator")
	public HyAdmin getOperator() {
		return this.operator;
	}

	public void setOperator(HyAdmin operator) {
		this.operator = operator;
	}

	@Column(name = "return_quantity")
	public Integer getReturnQuantity() {
		return this.returnQuantity;
	}

	public void setReturnQuantity(Integer returnQuantity) {
		this.returnQuantity = returnQuantity;
	}

}
