package com.hongyu.entity;
// Generated 2017-12-11 20:56:27 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConfirmDetail generated by hbm2java
 * 分公司打款确认单详情
 */
@Entity
@Table(name = "hy_confirm_detail")
public class ConfirmDetail implements java.io.Serializable {

	private Long id;
	private String type;
	private String orderCode;
	private String productId;
	private String productName;
	private String contact;
	private BigDecimal price;
	private BigDecimal deductionPoint;
	private BigDecimal discountServicer;
	private BigDecimal refund;
	private String remark;
	private Date reservationDate;
	private Date launchDate;
	private Date settlementDate;
	private Long confirmListId;

	public ConfirmDetail() {
	}

	public ConfirmDetail(String type, String orderCode, String productId, String productName, String contact,
			BigDecimal price, BigDecimal deductionPoint, BigDecimal discountServicer, BigDecimal refund, String remark,
			Date reservationDate, Date launchDate, Date settlementDate, Long confirmListId) {
		this.type = type;
		this.orderCode = orderCode;
		this.productId = productId;
		this.productName = productName;
		this.contact = contact;
		this.price = price;
		this.deductionPoint = deductionPoint;
		this.discountServicer = discountServicer;
		this.refund = refund;
		this.remark = remark;
		this.reservationDate = reservationDate;
		this.launchDate = launchDate;
		this.settlementDate = settlementDate;
		this.confirmListId = confirmListId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "order_code", nullable = false)
	public String getOrderCode() {
		return this.orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	@Column(name = "product_id", nullable = false)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "product_name", nullable = false)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "contact", nullable = false)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "price", nullable = false, precision = 21)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "deduction_point", nullable = false, precision = 21)
	public BigDecimal getDeductionPoint() {
		return this.deductionPoint;
	}

	public void setDeductionPoint(BigDecimal deductionPoint) {
		this.deductionPoint = deductionPoint;
	}

	@Column(name = "discount_servicer", nullable = false, precision = 21)
	public BigDecimal getDiscountServicer() {
		return this.discountServicer;
	}

	public void setDiscountServicer(BigDecimal discountServicer) {
		this.discountServicer = discountServicer;
	}

	@Column(name = "refund", nullable = false, precision = 21)
	public BigDecimal getRefund() {
		return this.refund;
	}

	public void setRefund(BigDecimal refund) {
		this.refund = refund;
	}

	@Column(name = "remark", nullable = false)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reservation_date", nullable = false, length = 10)
	public Date getReservationDate() {
		return this.reservationDate;
	}

	public void setReservationDate(Date reservationDate) {
		this.reservationDate = reservationDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "launch_date", nullable = false, length = 10)
	public Date getLaunchDate() {
		return this.launchDate;
	}

	public void setLaunchDate(Date launchDate) {
		this.launchDate = launchDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "settlement_date", nullable = false, length = 10)
	public Date getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Date settlementDate) {
		this.settlementDate = settlementDate;
	}

	@Column(name = "confirm_list_id", nullable = false)
	public Long getConfirmListId() {
		return this.confirmListId;
	}

	public void setConfirmListId(Long confirmListId) {
		this.confirmListId = confirmListId;
	}

}
