package com.hongyu.entity;
// Generated 2018-1-2 16:59:39 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyCoupon generated by hbm2java
 */
@Entity
@Table(name = "hy_coupon")
public class Coupon implements java.io.Serializable {

	private Long id;
	private String couponCode;
	private String issueType;
	private String useType;
	private Date issueTime;
	private Date thawingTime;
	private Integer validityPeriod;
	private Float sum;
	private Float balance;
	private String receiver;
	private String receiverPhone;
	private String activationCode;
	private String bindPhone;
	private Date bindPhoneTime;
	private Long bindWechatAccountId;
	private Date bindWechatTime;
	/**一次型 1:未绑定 2:未使用 3:已使用  4:过期        余额型  5:冻结 6:未绑定 7:已绑定*/
	private Integer state;   
	private Date useTime;
	private Date expireTime;
	/***/
	private Float couponCondition;  


	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "coupon_code")
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@Column(name = "issue_type")
	public String getIssueType() {
		return this.issueType;
	}

	public void setIssueType(String issueType) {
		this.issueType = issueType;
	}

	@Column(name = "use_type")
	public String getUseType() {
		return this.useType;
	}

	public void setUseType(String useType) {
		this.useType = useType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "issue_time")
	public Date getIssueTime() {
		return this.issueTime;
	}

	public void setIssueTime(Date issueTime) {
		this.issueTime = issueTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "thawing_time")
	public Date getThawingTime() {
		return this.thawingTime;
	}

	public void setThawingTime(Date thawingTime) {
		this.thawingTime = thawingTime;
	}

	@Column(name = "validity_period")
	public Integer getValidityPeriod() {
		return this.validityPeriod;
	}

	public void setValidityPeriod(Integer validityPeriod) {
		this.validityPeriod = validityPeriod;
	}

	@Column(name = "sum")
	public Float getSum() {
		return this.sum;
	}

	public void setSum(Float sum) {
		this.sum = sum;
	}

	@Column(name = "balance")
	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	@Column(name = "receiver")
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "receiver_phone")
	public String getReceiverPhone() {
		return this.receiverPhone;
	}

	public void setReceiverPhone(String receiverPhone) {
		this.receiverPhone = receiverPhone;
	}

	@Column(name = "activation_code")
	public String getActivationCode() {
		return this.activationCode;
	}

	public void setActivationCode(String activationCode) {
		this.activationCode = activationCode;
	}

	@Column(name = "bind_phone")
	public String getBindPhone() {
		return this.bindPhone;
	}

	public void setBindPhone(String bindPhone) {
		this.bindPhone = bindPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bind_phone_time")
	public Date getBindPhoneTime() {
		return this.bindPhoneTime;
	}

	public void setBindPhoneTime(Date bindPhoneTime) {
		this.bindPhoneTime = bindPhoneTime;
	}

	@Column(name = "bind_wechat_account_id")
	public Long getBindWechatAccountId() {
		return this.bindWechatAccountId;
	}

	public void setBindWechatAccountId(Long bindWechatAccountId) {
		this.bindWechatAccountId = bindWechatAccountId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bind_wechat_time")
	public Date getBindWechatTime() {
		return this.bindWechatTime;
	}

	public void setBindWechatTime(Date bindWechatTime) {
		this.bindWechatTime = bindWechatTime;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "use_time")
	public Date getUseTime() {
		return this.useTime;
	}

	public void setUseTime(Date useTime) {
		this.useTime = useTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_time")
	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	@Column(name = "coupon_condition")
	public Float getConponCondition() {
		return couponCondition;
	}

	public void setConponCondition(Float couponCondition) {
		this.couponCondition = couponCondition;
	}
}
