package com.hongyu.entity;
// Generated 2018-1-2 16:59:39 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyCouponRebateStatis generated by hbm2java
 */
@Entity
@Table(name = "hy_coupon_rebate_statis")
public class CouponRebateStatis implements java.io.Serializable {

	private Long id;
	private Integer issueType;
	private Float issueAmount;
	private Float rebateAmount;
	private Date startTime;
	private Date endTime;

	public CouponRebateStatis() {
	}

	public CouponRebateStatis(Long id) {
		this.id = id;
	}

	public CouponRebateStatis(Long id, Integer issueType, Float issueAmount, Float rebateAmount, Date startTime,
			Date endTime) {
		this.id = id;
		this.issueType = issueType;
		this.issueAmount = issueAmount;
		this.rebateAmount = rebateAmount;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "issue_type")
	public Integer getIssueType() {
		return this.issueType;
	}

	public void setIssueType(Integer issueType) {
		this.issueType = issueType;
	}

	@Column(name = "issue_amount", precision = 12, scale = 0)
	public Float getIssueAmount() {
		return this.issueAmount;
	}

	public void setIssueAmount(Float issueAmount) {
		this.issueAmount = issueAmount;
	}

	@Column(name = "rebate_amount", precision = 12, scale = 0)
	public Float getRebateAmount() {
		return this.rebateAmount;
	}

	public void setRebateAmount(Float rebateAmount) {
		this.rebateAmount = rebateAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
