package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyEmployeeAuditProcess generated by hbm2java
 */
@Entity
@Table(name = "hy_employee_audit_process")
public class EmployeeAuditProcess implements java.io.Serializable {

	private Long id;
	private Date createDate;
	private Date modifyDate;
	private EmployeeRegister employeeRegister;
	private HyAdmin auditor;
	private String stepName;
	private String auditadvice;
	private Integer passaudit;

	public EmployeeAuditProcess() {
	}

	public EmployeeAuditProcess(Long id) {
		this.id = id;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	@ManyToOne(fetch=FetchType.LAZY, cascade = CascadeType.REFRESH,optional = false)
	@JoinColumn(name = "employee_register_id")
	@JsonIgnore
	public EmployeeRegister getEmployeeRegister() {
		return employeeRegister;
	}

	public void setEmployeeRegister(EmployeeRegister employeeRegister) {
		this.employeeRegister = employeeRegister;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "auditor_id")
	public HyAdmin getAuditor() {
		return this.auditor;
	}

	public void setAuditor(HyAdmin auditor) {
		this.auditor = auditor;
	}

	@Column(name = "step_name")
	public String getStepName() {
		return this.stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	@Column(name = "auditadvice")
	public String getAuditadvice() {
		return this.auditadvice;
	}

	public void setAuditadvice(String auditadvice) {
		this.auditadvice = auditadvice;
	}

	@Column(name = "passaudit")
	public Integer getPassaudit() {
		return this.passaudit;
	}

	public void setPassaudit(Integer passaudit) {
		this.passaudit = passaudit;
	}
	@PrePersist
	public void prePersist(){
		this.setCreateDate(new Date());
	}
	@PreUpdate
	public void preUpdate(){
		this.setModifyDate(new Date());
	}

}
