package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.ibatis.annotations.One;

/**
 * HyEmployeeRegister generated by hbm2java
 */
@Entity
@Table(name = "hy_employee_register")
public class EmployeeRegister implements java.io.Serializable {

	private Long id;//主键
	private Date createtime;//创建时间
	private Date modifytime;//修改时间
	private String image;//图片
	private String name;//姓名
	private Boolean isMale;//性别，true男性，false女性
	private Date birthday;//生日
	private String idNumber;//身份证号
	private String address;//身份证地址
	private String nation;//民族
	private Integer height;//身高
	private BigDecimal weight;//体重
	private Boolean isMarried;//婚否
	private String politics;//政治面貌
	private String health;//健康状况
	private Integer workingSeniority;//从业年限
	private Long salary;//薪资要求
	private String degree;//学历
	private String profession;//专业
	private String graduatedSchool;//毕业学校
	private Boolean isOnBusiness;//是否出差
	private Boolean isOvertime;//能否加班
	
	private Department department;//所属部门
	
	private Position position;//所属岗位
	
	private Boolean isRegulated;//是否调剂
	private String mobile;//手机
	private Integer computerSkill;//计算机水平
	private String otherSkill;//其他技能
	private String hobby;//爱好
	private String firstMobile;//第一手机联系
	private String firstPhone;//第一座机联系
	private String address1;//常住地址1
	private String urgentPhone;//紧急座机联系
	private String urgentMobile;//紧急手机联系
	private String address2;//常住地址2
	
	private HyAdmin operator;//操作人
	
	private String remark;//备注
	private Date entrytime;//入职时间
	//private Date applicationTime;//申请时间
	private Integer jobStatus;//在职状态
	private Integer registerStatus;//状态
	
	private String username;//员工对应账号

	private String imageIdcard;
	private String imageDiploma;
	private List<EmployeeRegisterWork> employeeRegisterWorks;
	private List<EmployeeRegisterEducation> employeeRegisterEducations;
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifytime", length = 19)
	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_male")
	public Boolean getIsMale() {
		return this.isMale;
	}

	public void setIsMale(Boolean isMale) {
		this.isMale = isMale;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "id_number")
	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "nation")
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "weight", precision = 10, scale = 1)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "is_married")
	public Boolean getIsMarried() {
		return this.isMarried;
	}

	public void setIsMarried(Boolean isMarried) {
		this.isMarried = isMarried;
	}

	@Column(name = "politics")
	public String getPolitics() {
		return this.politics;
	}

	public void setPolitics(String politics) {
		this.politics = politics;
	}

	@Column(name = "health")
	public String getHealth() {
		return this.health;
	}

	public void setHealth(String health) {
		this.health = health;
	}

	@Column(name = "working_seniority")
	public Integer getWorkingSeniority() {
		return this.workingSeniority;
	}

	public void setWorkingSeniority(Integer workingSeniority) {
		this.workingSeniority = workingSeniority;
	}

	@Column(name = "salary", precision = 10, scale = 0)
	public Long getSalary() {
		return this.salary;
	}

	public void setSalary(Long salary) {
		this.salary = salary;
	}

	@Column(name = "degree")
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	@Column(name = "profession")
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "graduated_school")
	public String getGraduatedSchool() {
		return this.graduatedSchool;
	}

	public void setGraduatedSchool(String graduatedSchool) {
		this.graduatedSchool = graduatedSchool;
	}

	@Column(name = "is_on_business")
	public Boolean getIsOnBusiness() {
		return this.isOnBusiness;
	}

	public void setIsOnBusiness(Boolean isOnBusiness) {
		this.isOnBusiness = isOnBusiness;
	}

	@Column(name = "is_overtime")
	public Boolean getIsOvertime() {
		return this.isOvertime;
	}

	public void setIsOvertime(Boolean isOvertime) {
		this.isOvertime = isOvertime;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "department_id")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "position_id")
	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	@Column(name = "is_regulated")
	public Boolean getIsRegulated() {
		return this.isRegulated;
	}

	public void setIsRegulated(Boolean isRegulated) {
		this.isRegulated = isRegulated;
	}

	@Column(name = "mobile", length = 10)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "computer_skill")
	public Integer getComputerSkill() {
		return this.computerSkill;
	}

	public void setComputerSkill(Integer computerSkill) {
		this.computerSkill = computerSkill;
	}

	@Column(name = "other_skill")
	public String getOtherSkill() {
		return this.otherSkill;
	}

	public void setOtherSkill(String otherSkill) {
		this.otherSkill = otherSkill;
	}

	@Column(name = "hobby")
	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Column(name = "first_mobile")
	public String getFirstMobile() {
		return this.firstMobile;
	}

	public void setFirstMobile(String firstMobile) {
		this.firstMobile = firstMobile;
	}

	@Column(name = "first_phone")
	public String getFirstPhone() {
		return this.firstPhone;
	}

	public void setFirstPhone(String firstPhone) {
		this.firstPhone = firstPhone;
	}

	@Column(name = "address1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "urgent_phone")
	public String getUrgentPhone() {
		return this.urgentPhone;
	}

	public void setUrgentPhone(String urgentPhone) {
		this.urgentPhone = urgentPhone;
	}

	@Column(name = "urgent_mobile")
	public String getUrgentMobile() {
		return this.urgentMobile;
	}

	public void setUrgentMobile(String urgentMobile) {
		this.urgentMobile = urgentMobile;
	}

	@Column(name = "address2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "operator")
	public HyAdmin getOperator() {
		return this.operator;
	}

	public void setOperator(HyAdmin operator) {
		this.operator = operator;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entrytime", length = 10)
	public Date getEntrytime() {
		return this.entrytime;
	}

	public void setEntrytime(Date entrytime) {
		this.entrytime = entrytime;
	}

//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "application_time", length = 19)
//	public Date getApplicationTime() {
//		return this.applicationTime;
//	}
//
//	public void setApplicationTime(Date applicationTime) {
//		this.applicationTime = applicationTime;
//	}

	@Column(name = "job_status")
	public Integer getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(Integer jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Column(name = "register_status")
	public Integer getRegisterStatus() {
		return this.registerStatus;
	}

	public void setRegisterStatus(Integer registerStatus) {
		this.registerStatus = registerStatus;
	}
	@Column(name="username")
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	@Column(name="image_id_card")
	public String getImageIdcard() {
		return imageIdcard;
	}

	public void setImageIdcard(String imageIdcard) {
		this.imageIdcard = imageIdcard;
	}
	@Column(name="image_diploma")
	public String getImageDiploma() {
		return imageDiploma;
	}

	public void setImageDiploma(String imageDiploma) {
		this.imageDiploma = imageDiploma;
	}
	@OneToMany(fetch=FetchType.LAZY,mappedBy="employeeRegister",cascade=CascadeType.ALL,orphanRemoval = true)
	public List<EmployeeRegisterWork> getEmployeeRegisterWorks() {
		return employeeRegisterWorks;
	}

	public void setEmployeeRegisterWorks(List<EmployeeRegisterWork> employeeRegisterWorks) {
		this.employeeRegisterWorks = employeeRegisterWorks;
	}
	@OneToMany(fetch=FetchType.LAZY,mappedBy="employeeRegister",cascade=CascadeType.ALL,orphanRemoval = true)
	public List<EmployeeRegisterEducation> getEmployeeRegisterEducations() {
		return employeeRegisterEducations;
	}

	public void setEmployeeRegisterEducations(List<EmployeeRegisterEducation> employeeRegisterEducations) {
		this.employeeRegisterEducations = employeeRegisterEducations;
	}
	@PrePersist
	public void prePersist(){
		this.setCreatetime(new Date());
	}
	@PreUpdate
	public void preUpdate(){
		this.setModifytime(new Date());
	}
}
