package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyExperienceGroup generated by hbm2java
 */
@Entity
@Table(name = "hy_experience_group")
public class ExperienceGroup implements java.io.Serializable {

	private Long id;
	@JsonIgnore
	private Guide guide;
	private String line;
	private String vehicle;
	private Integer days;
	private Date date;
	private Integer member;
	private Integer clientProperty;
	private Integer workProperty;

	public ExperienceGroup() {
	}

	public ExperienceGroup(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@OneToOne(fetch=FetchType.LAZY,cascade=CascadeType.REFRESH)
	@JoinColumn(name = "guide_register_id")
	public Guide getGuide() {
		return this.guide;
	}

	public void setGuide(Guide guide) {
		this.guide = guide;
	}

	@Column(name = "line")
	public String getLine() {
		return this.line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	@Column(name = "vehicle")
	public String getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(String vehicle) {
		this.vehicle = vehicle;
	}

	@Column(name = "days")
	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "member")
	public Integer getMember() {
		return this.member;
	}

	public void setMember(Integer member) {
		this.member = member;
	}

	@Column(name = "client_property")
	public Integer getClientProperty() {
		return this.clientProperty;
	}

	public void setClientProperty(Integer clientProperty) {
		this.clientProperty = clientProperty;
	}

	@Column(name = "work_property")
	public Integer getWorkProperty() {
		return this.workProperty;
	}

	public void setWorkProperty(Integer workProperty) {
		this.workProperty = workProperty;
	}

}
