package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;


/**
 * HyExpose generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_expose")
public class Expose implements java.io.Serializable {

	private Long id;
	private String exposedPerson;
	private String content;
	private HyAdmin proposer;
	private HyAdmin operator;
	private Department department;
	private String phone;
	private Integer status;
	private List<ExposeReply> exposeReplies;
	private Date createDate;
	private Date modifyDate;

	public Expose() {
	}

	public Expose(Long id) {
		this.id = id;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "exposed_person")
	public String getExposedPerson() {
		return this.exposedPerson;
	}

	public void setExposedPerson(String exposedPerson) {
		this.exposedPerson = exposedPerson;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "proposer")
	public HyAdmin getProposer() {
		return this.proposer;
	}

	public void setProposer(HyAdmin proposer) {
		this.proposer = proposer;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "operator")
	public HyAdmin getOperator() {
		return operator;
	}

	public void setOperator(HyAdmin operator) {
		this.operator = operator;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "department")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	@OneToMany(fetch=FetchType.LAZY,mappedBy="expose")
	public List<ExposeReply> getExposeReplies() {
		return exposeReplies;
	}

	public void setExposeReplies(List<ExposeReply> exposeReplies) {
		this.exposeReplies = exposeReplies;
	}
	@PrePersist
	public void prePersist(){
		this.setCreateDate(new Date());
		this.setStatus(0);//0未处理,1已处理
	}
	@PreUpdate
	public void preUpdate(){
		this.setModifyDate(new Date());
	}

}
