package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyGuideAuditProcess generated by hbm2java
 */
@Entity
@Table(name = "hy_guide_audit_process")
public class GuideAuditProcess implements java.io.Serializable {

	private Long id;
	private Long applicationId;
	private Long auditor;
	private Integer stepName;
	private String auditadvice;
	private Date audittime;
	private Integer passaudit;

	public GuideAuditProcess() {
	}

	public GuideAuditProcess(Long id) {
		this.id = id;
	}
	public GuideAuditProcess(Long id, Long applicationId, Long auditor,
			Integer stepName, String auditadvice, Date audittime,
			Integer passaudit) {
		this.id = id;
		this.applicationId = applicationId;
		this.auditor = auditor;
		this.stepName = stepName;
		this.auditadvice = auditadvice;
		this.audittime = audittime;
		this.passaudit = passaudit;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "application_id")
	public Long getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Long applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "auditor")
	public Long getAuditor() {
		return this.auditor;
	}

	public void setAuditor(Long auditor) {
		this.auditor = auditor;
	}

	@Column(name = "step_name")
	public Integer getStepName() {
		return this.stepName;
	}

	public void setStepName(Integer stepName) {
		this.stepName = stepName;
	}

	@Column(name = "auditadvice")
	public String getAuditadvice() {
		return this.auditadvice;
	}

	public void setAuditadvice(String auditadvice) {
		this.auditadvice = auditadvice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "audittime", length = 19)
	public Date getAudittime() {
		return this.audittime;
	}

	public void setAudittime(Date audittime) {
		this.audittime = audittime;
	}

	@Column(name = "passaudit")
	public Integer getPassaudit() {
		return this.passaudit;
	}

	public void setPassaudit(Integer passaudit) {
		this.passaudit = passaudit;
	}

}
