package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hongyu.entity.HyLine.LineType;

/**
 * HyGuideAssignment generated by hbm2java
 */
@Entity
@Table(name = "hy_guide_assignment")
public class GuideAssignment implements java.io.Serializable {

	private Long id;//主键id
	private Date createDate;//创建时间
	private Date modifyDate;//修改时间
	private Long guideId;//导游id
	private Integer assignmentType;//派遣类型 0计调指派，1门店租借，2计调派单
	private Long groupId;//团id
	private LineType lineType;//qiche-汽车，guonei-国内，chujing-出境
	private Integer teamType;//0 : 散客   1 : 团队
	private Long orderId;//订单id
	private Integer serviceType;//服务类型,0全陪导游，1其他服务
	private Long qiangdanId;//抢单id
	private Date startDate;//开始日期
	private Date endDate;//结束日期
	private Integer days;//天数
	private String lineName;//线路名称
	private String travelProfile;//行程概要
	private String elseService;//其他服务内容
	private BigDecimal tip;//小费
	private BigDecimal serviceFee;//服务费
	private BigDecimal totalFee;//总费用
	private String operator;//派遣人
	private String operatorPhone;//派遣人电话
	private Date paiqianDate;//派遣时间
	private Date confirmDate;//确认或驳回时间
	private Date quxiaoDate;//取消时间
	private Integer status;//状态 0待确认，1已确认，2已驳回，3已取消
	private String reason;//驳回/取消理由
	private String visitorFeedbackQRcode;//游客反馈单二维码
	private Integer balanceStatus;//结算状态
	private Integer reviewStatus;//评价状态


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "guide_id")
	public Long getGuideId() {
		return this.guideId;
	}

	public void setGuideId(Long guideId) {
		this.guideId = guideId;
	}
	@Column(name="order_id")
	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "assignment_type")
	public Integer getAssignmentType() {
		return this.assignmentType;
	}

	public void setAssignmentType(Integer assignmentType) {
		this.assignmentType = assignmentType;
	}

	@Column(name = "group_id")
	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}
	@Column(name="line_type")
	public LineType getLineType() {
		return lineType;
	}

	public void setLineType(LineType lineType) {
		this.lineType = lineType;
	}
	@Column(name="team_type")
	public Integer getTeamType() {
		return teamType;
	}

	public void setTeamType(Integer teamType) {
		this.teamType = teamType;
	}

	@Column(name = "service_type")
	public Integer getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}
	@Column(name="qiangdan_id")
	public Long getQiangdanId() {
		return qiangdanId;
	}

	public void setQiangdanId(Long qiangdanId) {
		this.qiangdanId = qiangdanId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="end_date",length=10)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "days")
	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	@Column(name = "line_name")
	public String getLineName() {
		return this.lineName;
	}

	public void setLineName(String lineName) {
		this.lineName = lineName;
	}

	@Column(name = "travel_profile")
	public String getTravelProfile() {
		return this.travelProfile;
	}

	public void setTravelProfile(String travelProfile) {
		this.travelProfile = travelProfile;
	}

	@Column(name = "else_service")
	public String getElseService() {
		return this.elseService;
	}

	public void setElseService(String elseService) {
		this.elseService = elseService;
	}

	@Column(name = "tip", precision = 10)
	public BigDecimal getTip() {
		return this.tip;
	}

	public void setTip(BigDecimal tip) {
		this.tip = tip;
	}

	@Column(name = "service_fee", precision = 10)
	public BigDecimal getServiceFee() {
		return this.serviceFee;
	}

	public void setServiceFee(BigDecimal serviceFee) {
		this.serviceFee = serviceFee;
	}

	@Column(name = "total_fee", precision = 10)
	public BigDecimal getTotalFee() {
		return this.totalFee;
	}

	public void setTotalFee(BigDecimal totalFee) {
		this.totalFee = totalFee;
	}
	@Column(name="operator")
	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}
	@Column(name="operator_phone")
	public String getOperatorPhone() {
		return operatorPhone;
	}

	public void setOperatorPhone(String operatorPhone) {
		this.operatorPhone = operatorPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paiqian_date", length = 19)
	public Date getPaiqianDate() {
		return this.paiqianDate;
	}

	public void setPaiqianDate(Date paiqianDate) {
		this.paiqianDate = paiqianDate;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="quxiao_date")
	public Date getQuxiaoDate() {
		return quxiaoDate;
	}

	public void setQuxiaoDate(Date quxiaoDate) {
		this.quxiaoDate = quxiaoDate;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="confirm_date")
	public Date getConfirmDate() {
		return confirmDate;
	}

	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "reason")
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "visitor_feedback_QRcode")
	public String getVisitorFeedbackQRcode() {
		return this.visitorFeedbackQRcode;
	}

	public void setVisitorFeedbackQRcode(String visitorFeedbackQRcode) {
		this.visitorFeedbackQRcode = visitorFeedbackQRcode;
	}
	@Column(name="balance_status")
	public Integer getBalanceStatus() {
		return balanceStatus;
	}

	public void setBalanceStatus(Integer balanceStatus) {
		this.balanceStatus = balanceStatus;
	}
	
	@Column(name="review_status")
	public Integer getReviewStatus() {
		return reviewStatus;
	}
	public void setReviewStatus(Integer reviewStatus) {
		this.reviewStatus = reviewStatus;
	}

	@PrePersist
	public void prePersist(){
		this.setCreateDate(new Date());
		this.setBalanceStatus(0);
	}
	@PreUpdate
	public void preUpdate(){
		this.setModifyDate(new Date());
	}

}
