package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyGuideReviewDetail generated by hbm2java
 */
@Entity
@Table(name = "hy_guide_review_detail")
public class GuideReviewDetail implements java.io.Serializable {

	private Long id;
	private Long guideId;
	private String guideSn;
	private Integer type;
	private Integer guideType;
	private Long groupId;
	private Long orderId;
	private Long paiqianId;
	private String lineSn;
	private Date startDate;
	private Date testDate;
	private String content;
	private Integer score;
	private Integer starLevel;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "guide_sn")
	public String getGuideSn() {
		return this.guideSn;
	}
	
	public void setGuideSn(String guideSn) {
		this.guideSn = guideSn;
	}
	
	@Column(name = "guide_id")
	public Long getGuideId(){
		return this.guideId;
	}
	
	public void setGuideId(Long guideId){
		this.guideId = guideId;
	}
	
	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "guide_type")
	public Integer getGuideType() {
		return this.guideType;
	}

	public void setGuideType(Integer guideType) {
		this.guideType = guideType;
	}

	@Column(name = "group_id")
	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}
	@Column(name="order_id")
	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}
	@Column(name="paiqian_id")
	public Long getPaiqianId() {
		return paiqianId;
	}

	public void setPaiqianId(Long paiqianId) {
		this.paiqianId = paiqianId;
	}

	@Column(name = "line_sn")
	public String getLineSn() {
		return this.lineSn;
	}

	public void setLineSn(String lineSn) {
		this.lineSn = lineSn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "test_date", length = 10)
	public Date getTestDate() {
		return this.testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "star_level")
	public Integer getStarLevel() {
		return this.starLevel;
	}

	public void setStarLevel(Integer starLevel) {
		this.starLevel = starLevel;
	}

}
