package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyGuideRegister generated by hbm2java
 */
@Entity
@Table(name = "hy_guide")
public class Guide implements java.io.Serializable {

	private Long id;//导游注册id
	private String guideSn;//导游编号F/MYYYYMMDDXXX,最后三位递增
	private String name;//姓名
	private Integer sex;//性别 0女1男
	private String idNumber;//身份证号
	private Boolean hasCertificate;//是否有导游证 false没有true有
	private String phone;//手机
	private Integer rank;//导游级别 0高级，1中级，2初级
	private String touristCertificateNumber;//导游证号
	private Integer degree;//学历 0本科，1专科，2在读，3其他
	private String profession;//专业
	private String graduate;//毕业学校
	private Date graduateTime;//毕业时间
	private String hobby;//特长
	private String address;//家庭地址
	private String bankName;//开户行
	private String accountName;//开户名称
	private String bankAccount;//银行账号
	private String bankLink;//银行联行号
	private Date applicationTime;//申请时间
//	private Date createDate;//创建日期
	private Date modifyDate;//修改时间
//	private Language languages;
	
	private Integer status;//状态 0注册审核中，1已审核，2注册已驳回，3黑名单,4修改审核中，5修改已驳回
	private Boolean isIndividual1;//是否散客
	private Boolean isGroup;//是否团队
	private Boolean isStudent;//是否学生
	private Boolean isOld;//是否老年
	private Boolean isEnterprise;//是否企业单位
	private Boolean isIndividual2;//是否散客
	private Boolean isElse1;//是否其他1
	private String text1;//其他文本1
	private Boolean isSights;//是否风景类
	private Boolean isAncient;//是否古迹类
	private Boolean isHumanity;//是否人文类
	private Boolean isEntertainment;//是否娱乐类
	private Boolean isElse2;//是否其他2
	private String text2;//其他文本2
	private Boolean isSign;//是否会唱歌
	private Boolean isDance;//是否会跳舞
	private Boolean isStory;//是否会叫故事
	private Boolean isElse3;//是否其他3
	private String text3;//其他文本3

	private String idcardFront;//身份证正面
	private String idcardContrary;//身份证背面
	private String idcardInhand;//手持身份证
	private String touristCertificate;//导游证
	
	private String auditor;//审核人
	private String auditoradvice;//审核意见
	private Date audittime;//审核时间
	private Integer zongheLevel;//综合星级
	
	private String openId;//微信openId
	private List<ExperienceGroup> experienceGroups;//带团经历
	private List<ExperienceWork> experienceWorks;//工作经历
	private List<GuideLanguage> guideLanguages;//语种

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
//	@ManyToOne(fetch=FetchType.LAZY)
//	@JoinColumn(name="languages")
//	public Language getLanguages() {
//		return languages;
//	}
//
//	public void setLanguages(Language languages) {
//		this.languages = languages;
//	}
	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "id_number")
	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String IdNumber) {
		this.idNumber = IdNumber;
	}

	@Column(name = "has_certificate")
	public Boolean getHasCertificate() {
		return this.hasCertificate;
	}

	public void setHasCertificate(Boolean hasCertificate) {
		this.hasCertificate = hasCertificate;
	}

	@Column(name = "phone",unique=true,nullable=false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@Column(name = "tourist_certificate_number")
	public String getTouristCertificateNumber() {
		return this.touristCertificateNumber;
	}

	public void setTouristCertificateNumber(String touristCertificateNumber) {
		this.touristCertificateNumber = touristCertificateNumber;
	}

	@Column(name = "degree")
	public Integer getDegree() {
		return this.degree;
	}

	public void setDegree(Integer degree) {
		this.degree = degree;
	}

	@Column(name = "profession")
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "graduate")
	public String getGraduate() {
		return this.graduate;
	}

	public void setGraduate(String graduate) {
		this.graduate = graduate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "graduate_time", length = 10)
	public Date getGraduateTime() {
		return this.graduateTime;
	}

	public void setGraduateTime(Date graduateTime) {
		this.graduateTime = graduateTime;
	}

	@Column(name = "hobby")
	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "application_time", length = 19)
	public Date getApplicationTime() {
		return this.applicationTime;
	}

	public void setApplicationTime(Date applicationTime) {
		this.applicationTime = applicationTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "is_individual1")
	public Boolean getIsIndividual1() {
		return this.isIndividual1;
	}

	public void setIsIndividual1(Boolean isIndividual1) {
		this.isIndividual1 = isIndividual1;
	}

	@Column(name = "is_group")
	public Boolean getIsGroup() {
		return this.isGroup;
	}

	public void setIsGroup(Boolean isGroup) {
		this.isGroup = isGroup;
	}

	@Column(name = "is_student")
	public Boolean getIsStudent() {
		return this.isStudent;
	}

	public void setIsStudent(Boolean isStudent) {
		this.isStudent = isStudent;
	}

	@Column(name = "is_old")
	public Boolean getIsOld() {
		return this.isOld;
	}

	public void setIsOld(Boolean isOld) {
		this.isOld = isOld;
	}

	@Column(name = "is_enterprise")
	public Boolean getIsEnterprise() {
		return this.isEnterprise;
	}

	public void setIsEnterprise(Boolean isEnterprise) {
		this.isEnterprise = isEnterprise;
	}

	@Column(name = "is_individual2")
	public Boolean getIsIndividual2() {
		return this.isIndividual2;
	}

	public void setIsIndividual2(Boolean isIndividual2) {
		this.isIndividual2 = isIndividual2;
	}

	@Column(name = "is_else1")
	public Boolean getIsElse1() {
		return this.isElse1;
	}

	public void setIsElse1(Boolean isElse1) {
		this.isElse1 = isElse1;
	}

	@Column(name = "text1")
	public String getText1() {
		return this.text1;
	}

	public void setText1(String text1) {
		this.text1 = text1;
	}

	@Column(name = "is_sights")
	public Boolean getIsSights() {
		return this.isSights;
	}

	public void setIsSights(Boolean isSights) {
		this.isSights = isSights;
	}

	@Column(name = "is_ancient")
	public Boolean getIsAncient() {
		return this.isAncient;
	}

	public void setIsAncient(Boolean isAncient) {
		this.isAncient = isAncient;
	}

	@Column(name = "is_humanity")
	public Boolean getIsHumanity() {
		return this.isHumanity;
	}

	public void setIsHumanity(Boolean isHumanity) {
		this.isHumanity = isHumanity;
	}

	@Column(name = "is_entertainment")
	public Boolean getIsEntertainment() {
		return this.isEntertainment;
	}

	public void setIsEntertainment(Boolean isEntertainment) {
		this.isEntertainment = isEntertainment;
	}

	@Column(name = "is_else2")
	public Boolean getIsElse2() {
		return this.isElse2;
	}

	public void setIsElse2(Boolean isElse2) {
		this.isElse2 = isElse2;
	}

	@Column(name = "text2")
	public String getText2() {
		return this.text2;
	}

	public void setText2(String text2) {
		this.text2 = text2;
	}

	@Column(name = "is_sign")
	public Boolean getIsSign() {
		return this.isSign;
	}

	public void setIsSign(Boolean isSign) {
		this.isSign = isSign;
	}

	@Column(name = "is_dance")
	public Boolean getIsDance() {
		return this.isDance;
	}

	public void setIsDance(Boolean isDance) {
		this.isDance = isDance;
	}

	@Column(name = "is_story")
	public Boolean getIsStory() {
		return this.isStory;
	}

	public void setIsStory(Boolean isStory) {
		this.isStory = isStory;
	}

	@Column(name = "is_else3")
	public Boolean getIsElse3() {
		return this.isElse3;
	}

	public void setIsElse3(Boolean isElse3) {
		this.isElse3 = isElse3;
	}

	@Column(name = "text3")
	public String getText3() {
		return this.text3;
	}

	public void setText3(String text3) {
		this.text3 = text3;
	}

	@Column(name = "idcard_front")
	public String getIdcardFront() {
		return this.idcardFront;
	}

	public void setIdcardFront(String idcardFront) {
		this.idcardFront = idcardFront;
	}

	@Column(name = "idcard_contrary")
	public String getIdcardContrary() {
		return this.idcardContrary;
	}

	public void setIdcardContrary(String idcardContrary) {
		this.idcardContrary = idcardContrary;
	}

	@Column(name = "idcard_inhand")
	public String getIdcardInhand() {
		return this.idcardInhand;
	}

	public void setIdcardInhand(String idcardInhand) {
		this.idcardInhand = idcardInhand;
	}

	@Column(name = "tourist_certificate")
	public String getTouristCertificate() {
		return this.touristCertificate;
	}

	public void setTouristCertificate(String touristCertificate) {
		this.touristCertificate = touristCertificate;
	}
	@Column(name="guide_sn")
	public String getGuideSn() {
		return guideSn;
	}

	public void setGuideSn(String guideSn) {
		this.guideSn = guideSn;
	}
	@Column(name="bank_name")
	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
	@Column(name="account_name")
	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}
	@Column(name="bank_account")
	public String getBankAccount() {
		return bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}
	@Column(name="bank_link")
	public String getBankLink() {
		return bankLink;
	}

	public void setBankLink(String bankLink) {
		this.bankLink = bankLink;
	}
	@Column(name="auditor")
	public String getAuditor() {
		return auditor;
	}

	public void setAuditor(String auditor) {
		this.auditor = auditor;
	}
	@Column(name="auditoradvice")
	public String getAuditoradvice() {
		return auditoradvice;
	}

	public void setAuditoradvice(String auditoradvice) {
		this.auditoradvice = auditoradvice;
	}
	@Column(name="audittime")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getAudittime() {
		return audittime;
	}

	public void setAudittime(Date audittime) {
		this.audittime = audittime;
	}
	@Column(name="zonghe_level")
	public Integer getZongheLevel() {
		return zongheLevel;
	}

	public void setZongheLevel(Integer zongheLevel) {
		this.zongheLevel = zongheLevel;
	}
	@Column(name="open_id")
	public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@OneToMany(fetch=FetchType.LAZY,mappedBy="guide",cascade=CascadeType.ALL,orphanRemoval=true)
	public List<ExperienceGroup> getExperienceGroups() {
		return experienceGroups;
	}

	public void setExperienceGroups(List<ExperienceGroup> experienceGroups) {
		this.experienceGroups = experienceGroups;
	}

	@OneToMany(fetch=FetchType.LAZY,mappedBy="guide",cascade=CascadeType.ALL,orphanRemoval=true)
	public List<ExperienceWork> getExperienceWorks() {
		return experienceWorks;
	}

	public void setExperienceWorks(List<ExperienceWork> experienceWorks) {
		this.experienceWorks = experienceWorks;
	}

	@OneToMany(fetch=FetchType.LAZY,mappedBy="guide",cascade=CascadeType.ALL,orphanRemoval=true)
	public List<GuideLanguage> getGuideLanguages() {
		return guideLanguages;
	}

	public void setGuideLanguages(List<GuideLanguage> guideLanguages) {
		this.guideLanguages = guideLanguages;
	}
	@PrePersist
	public void prePersist(){
		this.setApplicationTime(new Date());
		this.setStatus(0);
		this.setZongheLevel(0);
	}
	@PreUpdate
	public void preUpdate(){
		this.setModifyDate(new Date());
	}
}
