package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyGuideReviewFormScore generated by hbm2java
 */
@Entity
@Table(name = "hy_guide_review_form_score")
public class GuideReviewFormScore implements java.io.Serializable {
	private Long id;
	@JsonIgnore
	private GuideReviewForm guideReviewForm;
	private String item;
	private Integer serviceType;
	private Integer scoreItem;
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="id",unique=true,nullable=false)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	@ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.REFRESH)
	@JoinColumn(name="guide_review_form_id")
	public GuideReviewForm getGuideReviewForm() {
		return guideReviewForm;
	}
	public void setGuideReviewForm(GuideReviewForm guideReviewForm) {
		this.guideReviewForm = guideReviewForm;
	}
	@Column(name="item")
	public String getItem() {
		return item;
	}
	public void setItem(String item) {
		this.item = item;
	}
	@Column(name="service_type")
	public Integer getServiceType() {
		return serviceType;
	}
	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}
	@Column(name="score_item")
	public Integer getScoreItem() {
		return scoreItem;
	}
	public void setScoreItem(Integer scoreItem) {
		this.scoreItem = scoreItem;
	}

}
