package com.hongyu.entity;
// Generated 2017-12-26 10:56:09 by Hibernate Tools 3.6.0.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.grain.entity.BaseEntity;

/**
 * HyArea generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_area")
public class HyArea extends BaseEntity {
	
	/** 树路径分隔符 */
	public static final String TREE_PATH_SEPARATOR = ",";
	private HyArea hyArea;
	private String fullName;
	private String name;
	private Boolean status;
	private String treePath;
	private Set<HyArea> hyAreas = new HashSet<HyArea>();
	private Integer order;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pID")
	public HyArea getHyArea() {
		return this.hyArea;
	}

	public void setHyArea(HyArea hyArea) {
		this.hyArea = hyArea;
	}

	@JsonProperty
	@Column(name = "full_name")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	@JsonProperty
	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@JsonProperty
	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(mappedBy = "hyArea", fetch = FetchType.LAZY)
	@OrderBy("id asc")
	public Set<HyArea> getHyAreas() {
		return this.hyAreas;
	}

	public void setHyAreas(Set<HyArea> hyAreas) {
		this.hyAreas = hyAreas;
	}
	
	@JsonProperty
	@Column(name = "tree_path")
	public String getTreePath() {
		return treePath;
	}

	public void setTreePath(String treePath) {
		this.treePath = treePath;
	}
	@JsonProperty
	@Column(name = "orders")
	public Integer getOrder() {
		return order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}


	@Transient
	public List<Long> getTreePaths() {
		List<Long> treePaths = new ArrayList<Long>();
		String[] ids = StringUtils.split(getTreePath(), TREE_PATH_SEPARATOR);
		if (ids != null) {
			for (String id : ids) {
				if(!id.equals("0") && !id.equals("1"))
				treePaths.add(Long.valueOf(id));
			}
			treePaths.add(this.getId());
		}
		return treePaths;
	}
	@Transient
	public Boolean isLeaf() {
		return this.getHyAreas().size() == 0;
	}

	/**
	 * 持久化前处理
	 */
	@PrePersist
	public void prePersist() {
		this.setStatus(true);
		HyArea parent = getHyArea();
		if (parent != null && !parent.getName().equals("中国") && !parent.getName().equals("国际")) {
			setFullName(parent.getFullName() + getName());
			setTreePath(parent.getTreePath() + parent.getId() + TREE_PATH_SEPARATOR);
		} 
		else if(parent != null && (parent.getName().equals("中国") || parent.getName().equals("国际"))){
			setFullName(getName());
			setTreePath(parent.getTreePath() + parent.getId() + TREE_PATH_SEPARATOR);
		}
		else {
			setFullName(getName());
			setTreePath(TREE_PATH_SEPARATOR);
		}
	}

	/**
	 * 更新前处理
	 */
	@PreUpdate
	public void preUpdate() {
		HyArea parent = getHyArea();
		if (parent != null && !parent.getName().equals("中国") && !parent.getName().equals("国际")) {
			setFullName(parent.getFullName() + getName());
			setTreePath(parent.getTreePath() + parent.getId() + TREE_PATH_SEPARATOR);
		} 
		else if(parent != null && (parent.getName().equals("中国") || parent.getName().equals("国际"))){
			setFullName(getName());
			setTreePath(parent.getTreePath() + parent.getId() + TREE_PATH_SEPARATOR);
		}
		else {
			setFullName(getName());
			setTreePath(TREE_PATH_SEPARATOR);
		}
	}
}
