package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyCompany generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_company")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class HyCompany implements Serializable{

	public static  enum Period {
		
		/** 月结 */
		month,
		
		/** 季结 */
		quarter,
		
		/** 年结 */
		year,
	}
	private Long ID;
	
	/** 公司名称 */
	private String companyName;
	
	/** 公司营业执照 */
	private String companyPic;

	/** 对应的部门 */
	private Department hyDepartment;
	
	/** 是否是总公司 */
	private Boolean isHead;
	
	/** 法人 */
	private String legalPerson;
	
	/** 电话 */
	private String mobile;
	
	/** 地址 */
	private String address;
	
	/** 其他资质 */
	private String otherAuthority;
	
	/** 分成周期 */
	private Period period;
	
	/** 信息创建人 */
	private HyAdmin creator;
	
	/** 负责人 */
	private HyAdmin principal;
	
	/** 分成比例  **/
	private BigDecimal dividePercent;

	/** 银行列表 */
	private Set<BankList> bankLists = new HashSet<BankList>(0);

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getID() {
		return ID;
	}

	public void setID(Long iD) {
		ID = iD;
	}

	@Column(name = "company_name")
	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name="company_pic")
	public String getCompanyPic() {
		return companyPic;
	}

	public void setCompanyPic(String companyPic) {
		this.companyPic = companyPic;
	}
	
	@ManyToOne
	@JoinColumn(name = "department")
	public Department getHyDepartment() {
		return this.hyDepartment;
	}

	public void setHyDepartment(Department hyDepartment) {
		this.hyDepartment = hyDepartment;
	}

	@Column(name = "is_head")
	public Boolean getIsHead() {
		return this.isHead;
	}

	public void setIsHead(Boolean isHead) {
		this.isHead = isHead;
	}

	@Column(name = "legalPerson", length = 20)
	public String getLegalPerson() {
		return this.legalPerson;
	}

	public void setLegalPerson(String legalPerson) {
		this.legalPerson = legalPerson;
	}

	@Column(name = "mobile", length = 50)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "other_authority")
	public String getOtherAuthority() {
		return this.otherAuthority;
	}

	public void setOtherAuthority(String otherAuthority) {
		this.otherAuthority = otherAuthority;
	}

	@Column(name = "period")
	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}
    
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "creator")
	public HyAdmin getCreator() {
		return creator;
	}
	public void setCreator(HyAdmin creator) {
		this.creator = creator;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "principal")
	public HyAdmin getPrincipal() {
		return principal;
	}

	public void setPrincipal(HyAdmin principal) {
		this.principal = principal;
	}
	
	@Column(name = "divide_percent")
	public BigDecimal getDividePercent() {
		return dividePercent;
	}

	public void setDividePercent(BigDecimal dividePercent) {
		this.dividePercent = dividePercent;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyCompany")
	public Set<BankList> getBankLists() {
		return this.bankLists;
	}

	public void setBankLists(Set<BankList> bankLists) {
		this.bankLists = bankLists;
	}


}
