package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyDepartmentModel generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_department_model")
public class HyDepartmentModel implements java.io.Serializable {


	private String name;
	private Set<Department> hyDepartments = new HashSet<Department>(0);


	@Id
	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyDepartmentModel")
	public Set<Department> getHyDepartments() {
		return this.hyDepartments;
	}

	public void setHyDepartments(Set<Department> hyDepartments) {
		this.hyDepartments = hyDepartments;
	}

}
