package com.hongyu.entity;
// default package
// Generated 2018-1-27 10:11:06 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyFullSubstract generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",
	"hyPromotion"
	})
@Table(name = "hy_full_substract")
public class HyFullSubstract implements java.io.Serializable {

	private Long id;
	private HyPromotion hyPromotion;
	private BigDecimal fullFreeAmount;
	private BigDecimal fullFreeRequirement;

	public HyFullSubstract() {
	}

	public HyFullSubstract(HyPromotion hyPromotion, BigDecimal fullFreeAmount, BigDecimal fullFreeRequirement) {
		this.hyPromotion = hyPromotion;
		this.fullFreeAmount = fullFreeAmount;
		this.fullFreeRequirement = fullFreeRequirement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id")
	public HyPromotion getHyPromotion() {
		return this.hyPromotion;
	}

	public void setHyPromotion(HyPromotion hyPromotion) {
		this.hyPromotion = hyPromotion;
	}

	@Column(name = "full_free_amount", precision = 10)
	public BigDecimal getFullFreeAmount() {
		return this.fullFreeAmount;
	}

	public void setFullFreeAmount(BigDecimal fullFreeAmount) {
		this.fullFreeAmount = fullFreeAmount;
	}

	@Column(name = "full_free_requirement", precision = 10)
	public BigDecimal getFullFreeRequirement() {
		return this.fullFreeRequirement;
	}

	public void setFullFreeRequirement(BigDecimal fullFreeRequirement) {
		this.fullFreeRequirement = fullFreeRequirement;
	}

}
