package com.hongyu.entity;
// default package
// Generated 2018-1-27 10:11:06 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyFullDiscount generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",
	"hyPromotion"
	})
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_full_discount")
public class HyFullDiscount implements java.io.Serializable {

	private Long id;
	private HyPromotion hyPromotion;
	private BigDecimal discountOff;
	private BigDecimal discountRequirenment;

	public HyFullDiscount() {
	}

	public HyFullDiscount(HyPromotion hyPromotion, BigDecimal discountOff, BigDecimal discountRequirenment) {
		this.hyPromotion = hyPromotion;
		this.discountOff = discountOff;
		this.discountRequirenment = discountRequirenment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id")
	public HyPromotion getHyPromotion() {
		return this.hyPromotion;
	}

	public void setHyPromotion(HyPromotion hyPromotion) {
		this.hyPromotion = hyPromotion;
	}

	@Column(name = "discount_off", precision = 10)
	public BigDecimal getDiscountOff() {
		return this.discountOff;
	}

	public void setDiscountOff(BigDecimal discountOff) {
		this.discountOff = discountOff;
	}

	@Column(name = "discount_requirenment", precision = 10)
	public BigDecimal getDiscountRequirenment() {
		return this.discountRequirenment;
	}

	public void setDiscountRequirenment(BigDecimal discountRequirenment) {
		this.discountRequirenment = discountRequirenment;
	}

}
