package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Digits;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyGroupOtherpriceSwd generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",
	})
@Table(name = "hy_group_otherprice_swd")
public class HyGroupOtherpriceSwd implements java.io.Serializable {

	private Long id;//id
	private HyGroup hygroup;//group_id
	private Integer swdTimes;//times
	private HyGroupShenheSwd shenheSwd;
	private HyGroupOtherprice hyGroupOtherprice;//group_other_price

	@Digits(integer=10, fraction=2)
	private BigDecimal danfangchaPrice;//danfangcha_price
	@Digits(integer=10, fraction=2)
	private BigDecimal danfangchaPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal danfangchaPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal danfangchaPrice4;

	@Digits(integer=10, fraction=2)
	private BigDecimal buwopuPrice;//buwopu_price
	@Digits(integer=10, fraction=2)
	private BigDecimal buwopuPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal buwopuPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal buwopuPrice4;

	@Digits(integer=10, fraction=2)
	private BigDecimal bumenpiaoPrice;//bumenpiao_price
	@Digits(integer=10, fraction=2)
	private BigDecimal bumenpiaoPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal bumenpiaoPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal bumenpiaoPrice4;

	@Digits(integer=10, fraction=2)
	private BigDecimal ertongzhanchaungPrice;//ertongzhanchaung_price
	@Digits(integer=10, fraction=2)
	private BigDecimal ertongzhanchaungPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal ertongzhanchaungPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal ertongzhanchaungPrice4;

	@Digits(integer=10, fraction=2)
	private BigDecimal buchuangweiPrice;//buchuangwei_price
	@Digits(integer=10, fraction=2)
	private BigDecimal buchuangweiPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal buchuangweiPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal buchuangweiPrice4;



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public HyGroup getHygroup() {
		return hygroup;
	}

	public void setHygroup(HyGroup hygroup) {
		this.hygroup = hygroup;
	}
	

	@Column(name = "times", precision = 10, scale = 0)
	public Integer getSwdTimes() {
		return swdTimes;
	}


	public void setSwdTimes(Integer swdTimes) {
		this.swdTimes = swdTimes;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_other_price")
	public HyGroupOtherprice getHyGroupOtherprice() {
		return this.hyGroupOtherprice;
	}

	public void setHyGroupOtherprice(HyGroupOtherprice hyGroupOtherprice) {
		this.hyGroupOtherprice = hyGroupOtherprice;
	}

	
	@Column(name = "danfangcha_price", precision = 10, scale = 0)
	public BigDecimal getDanfangchaPrice() {
		return this.danfangchaPrice;
	}

	public void setDanfangchaPrice(BigDecimal danfangchaPrice) {
		this.danfangchaPrice = danfangchaPrice;
	}

	@Column(name = "danfangcha_price1", precision = 10, scale = 0)
	public BigDecimal getDanfangchaPrice1() {
		return this.danfangchaPrice1;
	}

	public void setDanfangchaPrice1(BigDecimal danfangchaPrice1) {
		this.danfangchaPrice1 = danfangchaPrice1;
	}

	
	
	@Column(name = "danfangcha_price6", precision = 10, scale = 0)
	public BigDecimal getDanfangchaPrice6() {
		return this.danfangchaPrice6;
	}
	
	public void setDanfangchaPrice6(BigDecimal danfangchaPrice6) {
		this.danfangchaPrice6 = danfangchaPrice6;
	}
	
	public void setDanfangchaPrice4(BigDecimal danfangchaPrice4) {
		this.danfangchaPrice4 = danfangchaPrice4;
	}

	@Column(name = "danfangcha_price4", precision = 10, scale = 0)
	public BigDecimal getDanfangchaPrice4() {
		return this.danfangchaPrice4;
	}

	


	@Column(name = "buwopu_price", precision = 10, scale = 0)
	public BigDecimal getBuwopuPrice() {
		return this.buwopuPrice;
	}

	public void setBuwopuPrice(BigDecimal buwopuPrice) {
		this.buwopuPrice = buwopuPrice;
	}

	@Column(name = "buwopu_price1", precision = 10, scale = 0)
	public BigDecimal getBuwopuPrice1() {
		return this.buwopuPrice1;
	}

	public void setBuwopuPrice1(BigDecimal buwopuPrice1) {
		this.buwopuPrice1 = buwopuPrice1;
	}

	@Column(name = "buwopu_price6", precision = 10, scale = 0)
	public BigDecimal getBuwopuPrice6() {
		return this.buwopuPrice6;
	}

	public void setBuwopuPrice6(BigDecimal buwopuPrice6) {
		this.buwopuPrice6 = buwopuPrice6;
	}
	
	@Column(name = "buwopu_price4", precision = 10, scale = 0)
	public BigDecimal getBuwopuPrice4() {
		return this.buwopuPrice4;
	}

	public void setBuwopuPrice4(BigDecimal buwopuPrice4) {
		this.buwopuPrice4 = buwopuPrice4;
	}

	@Column(name = "bumenpiao_price", precision = 10, scale = 0)
	public BigDecimal getBumenpiaoPrice() {
		return this.bumenpiaoPrice;
	}

	public void setBumenpiaoPrice(BigDecimal bumenpiaoPrice) {
		this.bumenpiaoPrice = bumenpiaoPrice;
	}

	@Column(name = "bumenpiao_price1", precision = 10, scale = 0)
	public BigDecimal getBumenpiaoPrice1() {
		return this.bumenpiaoPrice1;
	}

	public void setBumenpiaoPrice1(BigDecimal bumenpiaoPrice1) {
		this.bumenpiaoPrice1 = bumenpiaoPrice1;
	}

	@Column(name = "bumenpiao_price6", precision = 10, scale = 0)
	public BigDecimal getBumenpiaoPrice6() {
		return this.bumenpiaoPrice6;
	}

	public void setBumenpiaoPrice6(BigDecimal bumenpiaoPrice6) {
		this.bumenpiaoPrice6 = bumenpiaoPrice6;
	}

	@Column(name = "bumenpiao_price4", precision = 10, scale = 0)
	public BigDecimal getBumenpiaoPrice4() {
		return this.bumenpiaoPrice4;
	}

	public void setBumenpiaoPrice4(BigDecimal bumenpiaoPrice4) {
		this.bumenpiaoPrice4 = bumenpiaoPrice4;
	}
	

	@Column(name = "ertongzhanchaung_price", precision = 10, scale = 0)
	public BigDecimal getErtongzhanchaungPrice() {
		return this.ertongzhanchaungPrice;
	}

	public void setErtongzhanchaungPrice(BigDecimal ertongzhanchaungPrice) {
		this.ertongzhanchaungPrice = ertongzhanchaungPrice;
	}

	@Column(name = "ertongzhanchaung_price1", precision = 10, scale = 0)
	public BigDecimal getErtongzhanchaungPrice1() {
		return this.ertongzhanchaungPrice1;
	}

	public void setErtongzhanchaungPrice1(BigDecimal ertongzhanchaungPrice1) {
		this.ertongzhanchaungPrice1 = ertongzhanchaungPrice1;
	}

	@Column(name = "ertongzhanchaung_price6", precision = 10, scale = 0)
	public BigDecimal getErtongzhanchaungPrice6() {
		return this.ertongzhanchaungPrice6;
	}

	public void setErtongzhanchaungPrice6(BigDecimal ertongzhanchaungPrice6) {
		this.ertongzhanchaungPrice6 = ertongzhanchaungPrice6;
	}

	@Column(name = "ertongzhanchaung_price4", precision = 10, scale = 0)
	public BigDecimal getErtongzhanchaungPrice4() {
		return this.ertongzhanchaungPrice4;
	}

	public void setErtongzhanchaungPrice4(BigDecimal ertongzhanchaungPrice4) {
		this.ertongzhanchaungPrice4 = ertongzhanchaungPrice4;
	}

	@Column(name = "buchuangwei_price", precision = 10, scale = 0)
	public BigDecimal getBuchuangweiPrice() {
		return this.buchuangweiPrice;
	}

	public void setBuchuangweiPrice(BigDecimal buchuangweiPrice) {
		this.buchuangweiPrice = buchuangweiPrice;
	}

	@Column(name = "buchuangwei_price1", precision = 10, scale = 0)
	public BigDecimal getBuchuangweiPrice1() {
		return this.buchuangweiPrice1;
	}

	public void setBuchuangweiPrice1(BigDecimal buchuangweiPrice1) {
		this.buchuangweiPrice1 = buchuangweiPrice1;
	}

	@Column(name = "buchuangwei_price6", precision = 10, scale = 0)
	public BigDecimal getBuchuangweiPrice6() {
		return this.buchuangweiPrice6;
	}

	public void setBuchuangweiPrice6(BigDecimal buchuangweiPrice6) {
		this.buchuangweiPrice6 = buchuangweiPrice6;
	}
	
	@Column(name = "buchuangwei_price4", precision = 10, scale = 0)
	public BigDecimal getBuchuangweiPrice4() {
		return this.buchuangweiPrice4;
	}

	public void setBuchuangweiPrice4(BigDecimal buchuangweiPrice4) {
		this.buchuangweiPrice4 = buchuangweiPrice4;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shenhe_swd")
	public HyGroupShenheSwd getShenheSwd() {
		return shenheSwd;
	}

	public void setShenheSwd(HyGroupShenheSwd shenheSwd) {
		this.shenheSwd = shenheSwd;
	}

}
