package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyGroupSpecialprice generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",
	"hyGroup",
	"hyGroupSpecialPriceSwds"
	})
@Table(name = "hy_group_specialprice")
public class HyGroupSpecialprice implements java.io.Serializable {

	private Long id;
	private HyGroup hyGroup;
	private Integer visitorNum;
	private BigDecimal specialPrice;
	private BigDecimal specialPrice1;
	private BigDecimal specialPrice4;
	private String intro;
	private Set<HyGroupSpecialPriceSwd> hyGroupSpecialPriceSwds = new HashSet<HyGroupSpecialPriceSwd>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public HyGroup getHyGroup() {
		return this.hyGroup;
	}

	public void setHyGroup(HyGroup hyGroup) {
		this.hyGroup = hyGroup;
	}

	@Column(name = "visitor_num")
	public Integer getVisitorNum() {
		return this.visitorNum;
	}

	public void setVisitorNum(Integer visitorNum) {
		this.visitorNum = visitorNum;
	}

	@Column(name = "special_price", precision = 20, scale = 2)
	public BigDecimal getSpecialPrice() {
		return this.specialPrice;
	}

	public void setSpecialPrice(BigDecimal specialPrice) {
		this.specialPrice = specialPrice;
	}

	@Column(name = "special_price1", precision = 20, scale = 2)
	public BigDecimal getSpecialPrice1() {
		return this.specialPrice1;
	}

	public void setSpecialPrice1(BigDecimal specialPrice1) {
		this.specialPrice1 = specialPrice1;
	}



	@Column(name = "intro")
	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyGroupSpecialprice", cascade={CascadeType.PERSIST,CascadeType.MERGE}, orphanRemoval=true)
	public Set<HyGroupSpecialPriceSwd> getHyGroupSpecialPriceSwds() {
		return this.hyGroupSpecialPriceSwds;
	}

	public void setHyGroupSpecialPriceSwds(Set<HyGroupSpecialPriceSwd> hyGroupSpecialPriceSwds) {
		this.hyGroupSpecialPriceSwds = hyGroupSpecialPriceSwds;
	}

	@Column(name = "special_price4", precision = 20, scale = 2)

	public BigDecimal getSpecialPrice4() {
		return specialPrice4;
	}

	public void setSpecialPrice4(BigDecimal specialPrice4) {
		this.specialPrice4 = specialPrice4;
	}

}
