package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Digits;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyGroupPriceSwd generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",

	})
@Table(name = "hy_group_price_swd")
public class HyGroupPriceSwd implements java.io.Serializable {

	//注意这些变量getter/setter要符合命名规范
	//仔细检查标注
	private Long id;//ID
	private HyGroup hygroup;//group_id
	private HyGroupPrice hyGroupPriceID;//group_price_id
	private HyGroupShenheSwd shenheSwd;
	private Integer swdTimes;//times
	private String startplace;//startplace
	
	//这下面的不用标注
	@Digits(integer=10, fraction=2)
	private BigDecimal adultPrice;//adult_price
	@Digits(integer=10, fraction=2)
	private BigDecimal adultPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal adultPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal adultPrice4;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal childrenPrice;//children_price
	@Digits(integer=10, fraction=2)
	private BigDecimal childrenPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal childrenPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal childrenPrice4;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal studentPrice;//student_price
	@Digits(integer=10, fraction=2)
	private BigDecimal studentPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal studentPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal studentPrice4;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal oldPrice;//old_price
	@Digits(integer=10, fraction=2)
	private BigDecimal oldPrice1;
	@Digits(integer=10, fraction=2)
	private BigDecimal oldPrice6;
	@Digits(integer=10, fraction=2)
	private BigDecimal oldPrice4;


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public HyGroup getHygroup() {
		return hygroup;
	}

	public void setHygroup(HyGroup hygroup) {
		this.hygroup = hygroup;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_price_id")
	public HyGroupPrice getHyGroupPriceID() {
		return this.hyGroupPriceID;
	}


	public void setHyGroupPriceID(HyGroupPrice hyGroupPriceID) {
		this.hyGroupPriceID = hyGroupPriceID;
	}

	@Column(name = "times")
	public Integer getSwdTimes() {
		return swdTimes;
	}

	public void setSwdTimes(Integer swdTimes) {
		this.swdTimes = swdTimes;
	}

	public String getStartplace() {
		return startplace;
	}

	public void setStartplace(String startplace) {
		this.startplace = startplace;
	}

	public BigDecimal getAdultPrice() {
		return adultPrice;
	}

	public void setAdultPrice(BigDecimal adultPrice) {
		this.adultPrice = adultPrice;
	}

	public BigDecimal getAdultPrice1() {
		return adultPrice1;
	}

	public void setAdultPrice1(BigDecimal adultPrice1) {
		this.adultPrice1 = adultPrice1;
	}

	public BigDecimal getAdultPrice6() {
		return adultPrice6;
	}

	public void setAdultPrice6(BigDecimal adultPrice6) {
		this.adultPrice6 = adultPrice6;
	}

	public BigDecimal getAdultPrice4() {
		return adultPrice4;
	}

	public void setAdultPrice4(BigDecimal adultPrice4) {
		this.adultPrice4 = adultPrice4;
	}

	public BigDecimal getChildrenPrice() {
		return childrenPrice;
	}

	public void setChildrenPrice(BigDecimal childrenPrice) {
		this.childrenPrice = childrenPrice;
	}

	public BigDecimal getChildrenPrice1() {
		return childrenPrice1;
	}

	public void setChildrenPrice1(BigDecimal childrenPrice1) {
		this.childrenPrice1 = childrenPrice1;
	}

	public BigDecimal getChildrenPrice6() {
		return childrenPrice6;
	}

	public void setChildrenPrice6(BigDecimal childrenPrice6) {
		this.childrenPrice6 = childrenPrice6;
	}

	public BigDecimal getChildrenPrice4() {
		return childrenPrice4;
	}

	public void setChildrenPrice4(BigDecimal childrenPrice4) {
		this.childrenPrice4 = childrenPrice4;
	}

	public BigDecimal getStudentPrice() {
		return studentPrice;
	}

	public void setStudentPrice(BigDecimal studentPrice) {
		this.studentPrice = studentPrice;
	}

	public BigDecimal getStudentPrice1() {
		return studentPrice1;
	}

	public void setStudentPrice1(BigDecimal studentPrice1) {
		this.studentPrice1 = studentPrice1;
	}

	public BigDecimal getStudentPrice6() {
		return studentPrice6;
	}

	public void setStudentPrice6(BigDecimal studentPrice6) {
		this.studentPrice6 = studentPrice6;
	}

	public BigDecimal getStudentPrice4() {
		return studentPrice4;
	}

	public void setStudentPrice4(BigDecimal studentPrice4) {
		this.studentPrice4 = studentPrice4;
	}

	public BigDecimal getOldPrice() {
		return oldPrice;
	}

	public void setOldPrice(BigDecimal oldPrice) {
		this.oldPrice = oldPrice;
	}

	public BigDecimal getOldPrice1() {
		return oldPrice1;
	}

	public void setOldPrice1(BigDecimal oldPrice1) {
		this.oldPrice1 = oldPrice1;
	}

	public BigDecimal getOldPrice6() {
		return oldPrice6;
	}

	public void setOldPrice6(BigDecimal oldPrice6) {
		this.oldPrice6 = oldPrice6;
	}

	public BigDecimal getOldPrice4() {
		return oldPrice4;
	}

	public void setOldPrice4(BigDecimal oldPrice4) {
		this.oldPrice4 = oldPrice4;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shenhe_swd")
	public HyGroupShenheSwd getShenheSwd() {
		return shenheSwd;
	}

	public void setShenheSwd(HyGroupShenheSwd shenheSwd) {
		this.shenheSwd = shenheSwd;
	}


	
	
}
