package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyGroupitemDetail generated by hbm2java
 */
@Entity
@Table(name = "hy_groupitem_detail")
public class HyGroupitemDetail implements java.io.Serializable {

	private Long id;
	private Integer buyNumber;
	private Date createTime;
	private String creator;
	private Long groupItemPromotionId;
	private Long itemId;
	private Long itemSpecificcationId;

	public HyGroupitemDetail() {
	}

	public HyGroupitemDetail(Integer buyNumber, Date createTime, String creator, Long groupItemPromotionId, Long itemId,
			Long itemSpecificcationId) {
		this.buyNumber = buyNumber;
		this.createTime = createTime;
		this.creator = creator;
		this.groupItemPromotionId = groupItemPromotionId;
		this.itemId = itemId;
		this.itemSpecificcationId = itemSpecificcationId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "buy_number")
	public Integer getBuyNumber() {
		return this.buyNumber;
	}

	public void setBuyNumber(Integer buyNumber) {
		this.buyNumber = buyNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "creator")
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "group_item_promotion_id")
	public Long getGroupItemPromotionId() {
		return this.groupItemPromotionId;
	}

	public void setGroupItemPromotionId(Long groupItemPromotionId) {
		this.groupItemPromotionId = groupItemPromotionId;
	}

	@Column(name = "item_id")
	public Long getItemId() {
		return this.itemId;
	}

	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	@Column(name = "item_specificcation_id")
	public Long getItemSpecificcationId() {
		return this.itemSpecificcationId;
	}

	public void setItemSpecificcationId(Long itemSpecificcationId) {
		this.itemSpecificcationId = itemSpecificcationId;
	}

}
