package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.validation.constraints.Digits;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyGroupPrice generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",
	"hyGroupPriceSwds",
	"hyGroup"
	})
@Table(name = "hy_group_price")
public class HyGroupPrice implements java.io.Serializable {

	private Long id;
	private HyGroup hyGroup;
	
	/** 团出发地 */
	private String startplace;
	
	/** 成人结算、外卖、官网售卖价 */
	@Digits(integer=20, fraction=2)
	private BigDecimal adultPrice;
	@Digits(integer=20, fraction=2)
	private BigDecimal adultPrice1;
	@Digits(integer=20, fraction=2)
	private BigDecimal adultPrice6;

	/** 儿童结算、外卖、官网售卖价 */
	@Digits(integer=20, fraction=2)
	private BigDecimal childrenPrice;
	@Digits(integer=20, fraction=2)
	private BigDecimal childrenPrice1;
	@Digits(integer=20, fraction=2)
	private BigDecimal childrenPrice6;


	/** 学生结算、外卖、官网售卖价 */
	@Digits(integer=20, fraction=2)
	private BigDecimal studentPrice;
	@Digits(integer=20, fraction=2)
	private BigDecimal studentPrice1;
	@Digits(integer=20, fraction=2)
	private BigDecimal studentPrice6;

	/** 老人结算、外卖、官网售卖价 */
	@Digits(integer=20, fraction=2)
	private BigDecimal oldPrice;
	@Digits(integer=20, fraction=2)
	private BigDecimal oldPrice1;
	@Digits(integer=20, fraction=2)
	private BigDecimal oldPrice6;
	
	/** 各类型价格结算退还价 */
	@Digits(integer=20, fraction=2)
	private BigDecimal adultPrice4;
	@Digits(integer=20, fraction=2)
	private BigDecimal childrenPrice4;
	@Digits(integer=20, fraction=2)
	private BigDecimal studentPrice4;
	@Digits(integer=20, fraction=2)
	private BigDecimal oldPrice4;
	
	private MhGroupPrice mhGroupPrice;
	
	private Set<HyGroupPriceSwd> hyGroupPriceSwds = new HashSet<HyGroupPriceSwd>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public HyGroup getHyGroup() {
		return this.hyGroup;
	}

	public void setHyGroup(HyGroup hyGroup) {
		this.hyGroup = hyGroup;
	}

	@Column(name = "startplace")
	public String getStartplace() {
		return this.startplace;
	}

	public void setStartplace(String startplace) {
		this.startplace = startplace;
	}

	

	@Column(name = "adult_price1")
	public BigDecimal getAdultPrice1() {
		return this.adultPrice1;
	}

	public void setAdultPrice1(BigDecimal adultPrice1) {
		this.adultPrice1 = adultPrice1;
	}

	@Column(name = "adult_price")
	public BigDecimal getAdultPrice() {
		return this.adultPrice;
	}

	public void setAdultPrice(BigDecimal adultPrice) {
		this.adultPrice = adultPrice;
	}

	@Column(name = "adult_price6")
	public BigDecimal getAdultPrice6() {
		return this.adultPrice6;
	}

	public void setAdultPrice6(BigDecimal adultPrice6) {
		this.adultPrice6 = adultPrice6;
	}

	@Column(name = "children_price1")
	public BigDecimal getChildrenPrice1() {
		return this.childrenPrice1;
	}

	public void setChildrenPrice1(BigDecimal childrenPrice1) {
		this.childrenPrice1 = childrenPrice1;
	}

	@Column(name = "children_price")
	public BigDecimal getChildrenPrice() {
		return this.childrenPrice;
	}

	public void setChildrenPrice(BigDecimal childrenPrice) {
		this.childrenPrice = childrenPrice;
	}

	@Column(name = "children_price6")
	public BigDecimal getChildrenPrice6() {
		return this.childrenPrice6;
	}

	public void setChildrenPrice6(BigDecimal childrenPrice6) {
		this.childrenPrice6 = childrenPrice6;
	}

	@Column(name = "student_price1")
	public BigDecimal getStudentPrice1() {
		return this.studentPrice1;
	}

	public void setStudentPrice1(BigDecimal studentPrice1) {
		this.studentPrice1 = studentPrice1;
	}

	@Column(name = "student_price")
	public BigDecimal getStudentPrice() {
		return this.studentPrice;
	}

	public void setStudentPrice(BigDecimal studentPrice) {
		this.studentPrice = studentPrice;
	}

	@Column(name = "student_price6")
	public BigDecimal getStudentPrice6() {
		return this.studentPrice6;
	}

	public void setStudentPrice6(BigDecimal studentPrice6) {
		this.studentPrice6 = studentPrice6;
	}


	@Column(name = "old_price1")
	public BigDecimal getOldPrice1() {
		return this.oldPrice1;
	}

	public void setOldPrice1(BigDecimal oldPrice1) {
		this.oldPrice1 = oldPrice1;
	}

	@Column(name = "old_price")
	public BigDecimal getOldPrice() {
		return this.oldPrice;
	}

	public void setOldPrice(BigDecimal oldPrice) {
		this.oldPrice = oldPrice;
	}

	@Column(name = "old_price6")
	public BigDecimal getOldPrice6() {
		return this.oldPrice6;
	}

	public void setOldPrice6(BigDecimal oldPrice6) {
		this.oldPrice6 = oldPrice6;
	}

	@Column(name = "adult_price4")
	public BigDecimal getAdultPrice4() {
		return this.adultPrice4;
	}

	public void setAdultPrice4(BigDecimal adultPrice4) {
		this.adultPrice4 = adultPrice4;
	}

	@Column(name = "children_price4")
	public BigDecimal getChildrenPrice4() {
		return this.childrenPrice4;
	}

	public void setChildrenPrice4(BigDecimal childrenPrice4) {
		this.childrenPrice4 = childrenPrice4;
	}

	@Column(name = "student_price4")
	public BigDecimal getStudentPrice4() {
		return this.studentPrice4;
	}

	public void setStudentPrice4(BigDecimal studentPrice4) {
		this.studentPrice4 = studentPrice4;
	}

	@Column(name = "old_price4")
	public BigDecimal getOldPrice4() {
		return this.oldPrice4;
	}

	public void setOldPrice4(BigDecimal oldPrice4) {
		this.oldPrice4 = oldPrice4;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyGroupPriceID", cascade={CascadeType.PERSIST,CascadeType.MERGE}, orphanRemoval=true)
	public Set<HyGroupPriceSwd> getHyGroupPriceSwds() {
		return this.hyGroupPriceSwds;
	}

	public void setHyGroupPriceSwds(Set<HyGroupPriceSwd> hyGroupPriceSwds) {
		this.hyGroupPriceSwds = hyGroupPriceSwds;
	}

	@OneToOne(fetch = FetchType.LAZY,mappedBy = "hyGroupPrice",cascade=CascadeType.ALL, orphanRemoval=true)
	public MhGroupPrice getMhGroupPrice() {
		return mhGroupPrice;
	}

	public void setMhGroupPrice(MhGroupPrice mhGroupPrice) {
		this.mhGroupPrice = mhGroupPrice;
	}
	
	
}
