package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HyHotel generated by hbm2java
 */
@Entity
@Table(name = "hy_hotel")
public class HyHotel implements java.io.Serializable {

	private Long id;
	private Long ticketSupplier;
	private Long creater;
	private String name;
	private Long area;
	private String address;
	private String reserveKnow;

	public HyHotel() {
	}

	public HyHotel(long id) {
		this.id = id;
	}

	public HyHotel(long id, Long ticketSupplier, Long creater, String name, Long area, String address,
			String reserveKnow) {
		this.id = id;
		this.ticketSupplier = ticketSupplier;
		this.creater = creater;
		this.name = name;
		this.area = area;
		this.address = address;
		this.reserveKnow = reserveKnow;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ticket_supplier")
	public Long getTicketSupplier() {
		return this.ticketSupplier;
	}

	public void setTicketSupplier(Long ticketSupplier) {
		this.ticketSupplier = ticketSupplier;
	}

	@Column(name = "creater")
	public Long getCreater() {
		return this.creater;
	}

	public void setCreater(Long creater) {
		this.creater = creater;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "area")
	public Long getArea() {
		return this.area;
	}

	public void setArea(Long area) {
		this.area = area;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "reserve_know")
	public String getReserveKnow() {
		return this.reserveKnow;
	}

	public void setReserveKnow(String reserveKnow) {
		this.reserveKnow = reserveKnow;
	}

}
