package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HyHotelsceneRoom generated by hbm2java
 */
@Entity
@Table(name = "hy_hotelscene_room")
public class HyHotelsceneRoom implements java.io.Serializable {

	private long id;
	private Long sceneHotel;
	private String type;
	private Boolean wifi;
	private Boolean window;
	private Boolean bathroom;
	private Integer available;
	private String breakfast;
	private String audit;
	private String oncarriage;

	public HyHotelsceneRoom() {
	}

	public HyHotelsceneRoom(long id) {
		this.id = id;
	}

	public HyHotelsceneRoom(long id, Long sceneHotel, String type, Boolean wifi, Boolean window, Boolean bathroom,
			Integer available, String breakfast, String audit, String oncarriage) {
		this.id = id;
		this.sceneHotel = sceneHotel;
		this.type = type;
		this.wifi = wifi;
		this.window = window;
		this.bathroom = bathroom;
		this.available = available;
		this.breakfast = breakfast;
		this.audit = audit;
		this.oncarriage = oncarriage;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "scene_hotel")
	public Long getSceneHotel() {
		return this.sceneHotel;
	}

	public void setSceneHotel(Long sceneHotel) {
		this.sceneHotel = sceneHotel;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "wifi")
	public Boolean getWifi() {
		return this.wifi;
	}

	public void setWifi(Boolean wifi) {
		this.wifi = wifi;
	}

	@Column(name = "window")
	public Boolean getWindow() {
		return this.window;
	}

	public void setWindow(Boolean window) {
		this.window = window;
	}

	@Column(name = "bathroom")
	public Boolean getBathroom() {
		return this.bathroom;
	}

	public void setBathroom(Boolean bathroom) {
		this.bathroom = bathroom;
	}

	@Column(name = "available")
	public Integer getAvailable() {
		return this.available;
	}

	public void setAvailable(Integer available) {
		this.available = available;
	}

	@Column(name = "breakfast")
	public String getBreakfast() {
		return this.breakfast;
	}

	public void setBreakfast(String breakfast) {
		this.breakfast = breakfast;
	}

	@Column(name = "audit")
	public String getAudit() {
		return this.audit;
	}

	public void setAudit(String audit) {
		this.audit = audit;
	}

	@Column(name = "oncarriage")
	public String getOncarriage() {
		return this.oncarriage;
	}

	public void setOncarriage(String oncarriage) {
		this.oncarriage = oncarriage;
	}

}
