package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyLineRefund generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",
	"line",
	})
@Table(name = "hy_line_refund")
public class HyLineRefund implements java.io.Serializable {

	private Long id;
	private Integer startDay;
	private Integer startTime;
	private Integer endDay;
	private Integer endTime;
	private BigDecimal percentage;
	private HyLine line;

    @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "start_day")
	public Integer getStartDay() {
		return this.startDay;
	}

	public void setStartDay(Integer startDay) {
		this.startDay = startDay;
	}

	@Column(name = "start_time")
	public Integer getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Integer startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_day")
	public Integer getEndDay() {
		return this.endDay;
	}

	public void setEndDay(Integer endDay) {
		this.endDay = endDay;
	}

	@Column(name = "end_time")
	public Integer getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Integer endTime) {
		this.endTime = endTime;
	}

	@Column(name = "percentage", precision = 20, scale = 2)
	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "line")
	public HyLine getLine() {
		return this.line;
	}

	public void setLine(HyLine line) {
		this.line = line;
	}

}
