package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyLineTravels generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",
						"line",
})
@Table(name = "hy_line_travels")
public class HyLineTravels implements java.io.Serializable {

	private Long id;
	private TransportEntity transport;
	private String route;
	private String restaurant;
	private Boolean isBreakfast;
	private Boolean isLunch;
	private Boolean isDinner;
	private HyLine line;


    @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transport")
	public TransportEntity getTransport() {
		return this.transport;
	}

	public void setTransport(TransportEntity transport) {
		this.transport = transport;
	}

	@Column(name = "route")
	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@Column(name = "restaurant")
	public String getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(String restaurant) {
		this.restaurant = restaurant;
	}

	@Column(name = "is_breakfast")
	public Boolean getIsBreakfast() {
		return this.isBreakfast;
	}

	public void setIsBreakfast(Boolean isBreakfast) {
		this.isBreakfast = isBreakfast;
	}

	@Column(name = "is_lunch")
	public Boolean getIsLunch() {
		return this.isLunch;
	}

	public void setIsLunch(Boolean isLunch) {
		this.isLunch = isLunch;
	}

	@Column(name = "is_dinner")
	public Boolean getIsDinner() {
		return this.isDinner;
	}

	public void setIsDinner(Boolean isDinner) {
		this.isDinner = isDinner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "line")
	public HyLine getLine() {
		return this.line;
	}

	public void setLine(HyLine line) {
		this.line = line;
	}

}
