package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyOrderCustomer generated by hbm2java
 */
@Entity
@Table(name = "hy_order_customer")
public class HyOrderCustomer implements java.io.Serializable {

	private Long id;//主键id
	@JsonIgnore
	private HyOrderItem orderItem;//所属条目
	private String name;//姓名
	private Integer type;//游客类型 0(成人)/1（儿童）/2（学生）/3（老人）
	private Integer gender;//性别 0女1男
	private Date birthday;//出生年月
	private Integer age;//年龄
	private String phone;//手机
	private Boolean isCoupon;//是否选择电子券
	
	private Boolean isInsurance;//是否选择其他保险
	private Long insuranceId;//保险id
	private BigDecimal salePrice;//外卖价
	private BigDecimal settlementPrice;//结算价
	
	private Integer certificateType;//证件类型0：身份证          1：护照        2：港澳台通行证 3：士兵证       4：回乡证

	private String certificate;//证件号
	private Date certificateTime;//证件有效期
	private String passportTime;//护照有效期
	private String country;//国籍
	private String surname;//名英文（拼音）
	private String firstname;//姓英文(拼音)

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public HyOrderItem getOrderItem() {
		return this.orderItem;
	}

	public void setOrderItem (HyOrderItem orderItem ) {
		this.orderItem = orderItem;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
	@Column(name="age")
	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	@Column(name="is_coupon")
	public Boolean getIsCoupon() {
		return isCoupon;
	}

	public void setIsCoupon(Boolean isCoupon) {
		this.isCoupon = isCoupon;
	}
	@Column(name="is_insurance")
	public Boolean getIsInsurance() {
		return isInsurance;
	}

	public void setIsInsurance(Boolean isInsurance) {
		this.isInsurance = isInsurance;
	}
	@Column(name="insurance_id")
	public Long getInsuranceId() {
		return insuranceId;
	}

	public void setInsuranceId(Long insuranceId) {
		this.insuranceId = insuranceId;
	}
	@Column(name="sale_price")
	public BigDecimal getSalePrice() {
		return salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}
	@Column(name="settlement_price")
	public BigDecimal getSettlementPrice() {
		return settlementPrice;
	}

	public void setSettlementPrice(BigDecimal settlementPrice) {
		this.settlementPrice = settlementPrice;
	}

	@Column(name = "certificate_type")
	public Integer getCertificateType() {
		return this.certificateType;
	}

	public void setCertificateType(Integer certificateType) {
		this.certificateType = certificateType;
	}

	@Column(name = "certificate")
	public String getCertificate() {
		return this.certificate;
	}

	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "certificate_time", length = 10)
	public Date getCertificateTime() {
		return this.certificateTime;
	}

	public void setCertificateTime(Date certificateTime) {
		this.certificateTime = certificateTime;
	}

	@Column(name = "passport_time")
	public String getPassportTime() {
		return this.passportTime;
	}

	public void setPassportTime(String passportTime) {
		this.passportTime = passportTime;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "surname")
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

}
