package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyOrderItem generated by hbm2java
 */
@Entity
@Table(name = "hy_order_item")
public class HyOrderItem implements java.io.Serializable {

	private Long id;//主键id
	//保险订单退款后，置为1,代表无效
	private Integer status;//条目状态0有效，1无效
	private Date modifytime;//更改时间
	private Date startDate;//所选服务开始日期
	private Date endDate;//结束日期
	private String name;//条目名称
	private Integer type;//订单条目类型0导游租赁，1线路，2订购门票，3酒店，4门票，5酒+景，6保险，7签证,8线路其他价格
	/**当订单条目类型type为1线路
	 * priceType：0普通成人价，1普通儿童价，2普通学生价，3普通老人价，4特殊价格
	 * 当订单条目类型type为8线路其他价格
	 * priceType：0单房差，1补卧铺，2补门票，3儿童占床，4补床位
	 */
	private Integer priceType;//价格类型	
	private BigDecimal jiesuanPrice;//结算价
	private BigDecimal waimaiPrice;//官网外卖价
	private Integer number;//数量
	private Integer numberOfReturn;//退货数量
	@JsonIgnore
	private HyOrder order;//所属订单
	private Long productId;//产品id
	private Long specificationId;	//规格id
	private Long priceId;//价格id
	private List<HyOrderCustomer> hyOrderCustomers;
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifytime", length = 19)
	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="start_date")
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="end_date")
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "price_type")
	public Integer getPriceType() {
		return this.priceType;
	}

	public void setPriceType(Integer priceType) {
		this.priceType = priceType;
	}

	@Column(name = "jiesuan_price", precision = 10)
	public BigDecimal getJiesuanPrice() {
		return this.jiesuanPrice;
	}

	public void setJiesuanPrice(BigDecimal jiesuanPrice) {
		this.jiesuanPrice = jiesuanPrice;
	}

	@Column(name = "waimai_price", precision = 10)
	public BigDecimal getWaimaiPrice() {
		return this.waimaiPrice;
	}

	public void setWaimaiPrice(BigDecimal waimaiPrice) {
		this.waimaiPrice = waimaiPrice;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "number_of_return")
	public Integer getNumberOfReturn() {
		return this.numberOfReturn;
	}

	public void setNumberOfReturn(Integer numberOfReturn) {
		this.numberOfReturn = numberOfReturn;
	}
	@ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.REFRESH)
	@JoinColumn(name = "order_id")
	public HyOrder getOrder() {
		return this.order;
	}

	public void setOrder(HyOrder order) {
		this.order = order;
	}

	@Column(name = "product_id")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "price_id")
	public Long getPriceId() {
		return this.priceId;
	}

	public void setPriceId(Long priceId) {
		this.priceId = priceId;
	}
	@OneToMany(fetch=FetchType.LAZY,mappedBy="orderItem",cascade=CascadeType.ALL)
	public List<HyOrderCustomer> getHyOrderCustomers() {
		return hyOrderCustomers;
	}

	public void setHyOrderCustomers(List<HyOrderCustomer> hyOrderCustomers) {
		this.hyOrderCustomers = hyOrderCustomers;
	}

	@PreUpdate
	public void preUpdate(){
		this.setModifytime(new Date());
	}

	@Column(name="specification_id")
	public Long getSpecificationId() {
		return specificationId;
	}

	public void setSpecificationId(Long specificationId) {
		this.specificationId = specificationId;
	}
}
