package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.hongyu.util.Constants.DeductLine;

/**
 * HyOrder generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_order")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class HyOrder implements java.io.Serializable {

	private Long id;//主键id
	private String orderNumber;//订单号
	private String name;//订单名称
	
	//租借导游订单状态：0待门店支付，1待门店确认，2待导游确认，3导游通过，4驳回待财务确认,5门店已取消，
					//6已驳回，7门店已退款，8导游已退款,9待评价，10已评价
	private Integer status;//订单状态0待门店支付，1待门店确认，2待供应商确认，3供应商通过，4驳回待财务确认,5已驳回,6已取消
	private Integer paystatus;//支付状态0待支付，1已支付
	
	
	private Integer checkstatus;//门店确认状态0待确认，1已确认,2已驳回
	
	//租借导游订单该字段为导游确认订单状态
	private Integer guideCheckStatus;	//导游确认订单状态，0未确认，1已确认，2已驳回
	


	private Integer refundstatus;//退款状态0未退款，1退款中，2全部已退款 3部分退款,4退款已驳回
	private Integer type;//订单类型0导游租赁，1线路，2订购门票，3酒店，4门票，5酒+景，6保险，7签证
	private Integer source;//订单来源0门店，1官网不选门店，2官网选择门店
	private Integer people;//人数
	
	private Integer storeType;//门店类型，0虹宇门店
	private Long storeId;//门店id
	private HyAdmin operator;//门店处理人id
	private String creatorId;//创建人id
	
	private BigDecimal adjustMoney;//调整金额
	private Integer discountedType;//优惠方式0每单满减，1每单打折，2每人减,3无促销
	private Long discountedId;//促销id
	private BigDecimal discountedPrice;//优惠金额
	
	private BigDecimal jiesuanMoney1;//除保险之外的订单条目的总结算价
	private BigDecimal jiusuanMoney;//订单结算价
	private BigDecimal waimaiMoney;//订单外卖价
	private BigDecimal jiesuanTuikuan;//结算退款价
	private BigDecimal waimaiTuikuan;//外卖退款价
	private BigDecimal baoxianJiesuanTuikuan;//保险结算退款价
	private BigDecimal baoxianWaimaiTuikuan;//保险外卖退款价
	private Boolean ifjiesuan;//是否结算
	private String insuranceOrderDownloadUrl;
	private Date jiesuantime;
	private Insurance insurance;
	
	private Integer koudianMethod;//扣点方式
	private BigDecimal proportion;//扣点比例
	private BigDecimal headProportion;//人头扣点
	private BigDecimal koudianMoney;//扣点金额
	
	private String departure;//出发地
	private Date fatuandate;//发团日期
	private Integer tianshu;//天数
	/*回团信息
	 * 当type=7，即为签证订单的时候，该字段用来存储邮寄地址
	 * 数据形式“XX省，XX市，XX区，详细地址，收货人，手机号”
	 * 用“，”隔开
	 * */
	private String huituanxinxi;
	private String xianlumingcheng;//线路名称
	private Integer xianlutype;//线路类型新类型(0汽车    1境内    2境外)(0汽车散客，1汽车团客，2国内散客，3国内团客，4出境散客，5出境团客)
	private Integer fuwutype;//服务类型
	private String xingchenggaiyao;//行程概要
	
	
	private BigDecimal tip;//小费
	private String tipInstruction;//小费说明
	private String contact;//联系人
	private String contactIdNumber;//联系人身份证
	private String phone;//联系电话
	private String remark;//备注
	private Long contractId;//合同主键id
	private String contractNumber;//合同编号
	private Integer contractType;//只有当订单类型为线路订单的时候，使用该值判断合同类型(0-一日游  1-国内游  2-出境游)
	
	private Date createtime;//创建时间
	private Date modifytime;//修改时间
	
	private List<HyOrderItem> orderItems;//订单条目
	
	private Long groupId;	//团id
	private HyAdmin supplier;//团所属线路计调
	
	private Boolean isDivideStatistic;	//是否分成统计
	
	private Date payTime;	//支付时间
	
	private BigDecimal storeFanLi;//门店返利
	
	/**用于按团号收款统计表,是否以对账*/
	private Boolean isCheckAccount=false;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "order_number")
	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "paystatus")
	public Integer getPaystatus() {
		return this.paystatus;
	}

	public void setPaystatus(Integer paystatus) {
		this.paystatus = paystatus;
	}

	@Column(name = "checkstatus")
	public Integer getCheckstatus() {
		return this.checkstatus;
	}

	public void setCheckstatus(Integer checkstatus) {
		this.checkstatus = checkstatus;
	}

	@Column(name = "refundstatus")
	public Integer getRefundstatus() {
		return this.refundstatus;
	}

	public void setRefundstatus(Integer refundstatus) {
		this.refundstatus = refundstatus;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "source")
	public Integer getSource() {
		return this.source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	@Column(name = "people")
	public Integer getPeople() {
		return this.people;
	}

	public void setPeople(Integer people) {
		this.people = people;
	}
	@Column(name="store_type")
	public Integer getStoreType() {
		return storeType;
	}

	public void setStoreType(Integer storeType) {
		this.storeType = storeType;
	}

	@Column(name = "store_id")
	public Long getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "operator_id")
	public HyAdmin getOperator() {
		return this.operator;
	}

	public void setOperator(HyAdmin operator) {
		this.operator = operator;
	}

	@Column(name = "creator_id")
	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	@Column(name = "adjust_money", precision = 10)
	public BigDecimal getAdjustMoney() {
		return this.adjustMoney;
	}

	public void setAdjustMoney(BigDecimal adjustMoney) {
		this.adjustMoney = adjustMoney;
	}
	@Column(name="discounted_type")
	public Integer getDiscountedType() {
		return discountedType;
	}

	public void setDiscountedType(Integer discountedType) {
		this.discountedType = discountedType;
	}
	@Column(name="discounted_id")
	public Long getDiscountedId() {
		return discountedId;
	}

	public void setDiscountedId(Long discountedId) {
		this.discountedId = discountedId;
	}

	@Column(name = "discounted_price", precision = 10)
	public BigDecimal getDiscountedPrice() {
		return this.discountedPrice;
	}

	public void setDiscountedPrice(BigDecimal discountedPrice) {
		this.discountedPrice = discountedPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifytime", length = 19)
	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	@Column(name = "jiesuan_money1", precision = 10)
	public BigDecimal getJiesuanMoney1() {
		return this.jiesuanMoney1;
	}

	public void setJiesuanMoney1(BigDecimal jiesuanMoney1) {
		this.jiesuanMoney1 = jiesuanMoney1;
	}

	@Column(name = "jiusuan_money", precision = 10)
	public BigDecimal getJiusuanMoney() {
		return this.jiusuanMoney;
	}

	public void setJiusuanMoney(BigDecimal jiusuanMoney) {
		this.jiusuanMoney = jiusuanMoney;
	}

	@Column(name = "waimai_money", precision = 10)
	public BigDecimal getWaimaiMoney() {
		return this.waimaiMoney;
	}

	public void setWaimaiMoney(BigDecimal waimaiMoney) {
		this.waimaiMoney = waimaiMoney;
	}

	@Column(name = "jiesuan_tuikuan", precision = 10)
	public BigDecimal getJiesuanTuikuan() {
		return this.jiesuanTuikuan;
	}

	public void setJiesuanTuikuan(BigDecimal jiesuanTuikuan) {
		this.jiesuanTuikuan = jiesuanTuikuan;
	}

	@Column(name = "ifjiesuan", precision = 10)
	public Boolean getIfjiesuan() {
		return this.ifjiesuan;
	}

	public void setIfjiesuan(Boolean ifjiesuan) {
		this.ifjiesuan = ifjiesuan;
	}

	@Column(name = "koudian_method")
	public Integer getKoudianMethod() {
		return this.koudianMethod;
	}

	public void setKoudianMethod(Integer koudianMethod) {
		this.koudianMethod = koudianMethod;
	}

	@Column(name = "proportion", precision = 10)
	public BigDecimal getProportion() {
		return this.proportion;
	}

	public void setProportion(BigDecimal proportion) {
		this.proportion = proportion;
	}

	@Column(name = "head_proportion", precision = 10)
	public BigDecimal getHeadProportion() {
		return this.headProportion;
	}

	public void setHeadProportion(BigDecimal headProportion) {
		this.headProportion = headProportion;
	}

	@Column(name = "koudian_money", precision = 10)
	public BigDecimal getKoudianMoney() {
		return this.koudianMoney;
	}

	public void setKoudianMoney(BigDecimal koudianMoney) {
		this.koudianMoney = koudianMoney;
	}

	@Column(name = "departure")
	public String getDeparture() {
		return this.departure;
	}

	public void setDeparture(String departure) {
		this.departure = departure;
	}

	@Temporal(TemporalType.DATE)
	@DateTimeFormat(iso=ISO.DATE)
	@Column(name = "fatuandate", length = 10)
	public Date getFatuandate() {
		return this.fatuandate;
	}

	public void setFatuandate(Date fatuandate) {
		this.fatuandate = fatuandate;
	}

	@Column(name = "tianshu")
	public Integer getTianshu() {
		return this.tianshu;
	}

	public void setTianshu(Integer tianshu) {
		this.tianshu = tianshu;
	}

	@Column(name = "huituanxinxi")
	public String getHuituanxinxi() {
		return this.huituanxinxi;
	}

	public void setHuituanxinxi(String huituanxinxi) {
		this.huituanxinxi = huituanxinxi;
	}

	@Column(name = "xianlumingcheng")
	public String getXianlumingcheng() {
		return this.xianlumingcheng;
	}

	public void setXianlumingcheng(String xianlumingcheng) {
		this.xianlumingcheng = xianlumingcheng;
	}

	@Column(name = "xianlutype")
	public Integer getXianlutype() {
		return this.xianlutype;
	}

	public void setXianlutype(Integer xianlutype) {
		this.xianlutype = xianlutype;
	}

	@Column(name = "fuwutype")
	public Integer getFuwutype() {
		return this.fuwutype;
	}

	public void setFuwutype(Integer fuwutype) {
		this.fuwutype = fuwutype;
	}

	@Column(name = "xingchenggaiyao")
	public String getXingchenggaiyao() {
		return this.xingchenggaiyao;
	}

	public void setXingchenggaiyao(String xingchenggaiyao) {
		this.xingchenggaiyao = xingchenggaiyao;
	}


	@Column(name="tip")
	public BigDecimal getTip() {
		return tip;
	}

	public void setTip(BigDecimal tip) {
		this.tip = tip;
	}
	@Column(name="tip_instruction")
	public String getTipInstruction() {
		return tipInstruction;
	}

	public void setTipInstruction(String tipInstruction) {
		this.tipInstruction = tipInstruction;
	}

	@Column(name = "contact")
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "contact_id_number")
	public String getContactIdNumber() {
		return contactIdNumber;
	}

	public void setContactIdNumber(String contactIdNumber) {
		this.contactIdNumber = contactIdNumber;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "contract_id")
	public Long getContractId() {
		return this.contractId;
	}

	public void setContractId(Long contractId) {
		this.contractId = contractId;
	}
	@Column(name = "contract_number")
	public String getContractNumber() {
		return contractNumber;
	}

	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}
	@Column(name = "contract_type")
	public Integer getContractType() {
		return contractType;
	}

	public void setContractType(Integer contractType) {
		this.contractType = contractType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
	@OneToMany(fetch=FetchType.LAZY,mappedBy="order",cascade=CascadeType.ALL,orphanRemoval=true)
	public List<HyOrderItem> getOrderItems() {
		return orderItems;
	}

	public void setOrderItems(List<HyOrderItem> orderItems) {
		this.orderItems = orderItems;
	}
	
	@PrePersist
	public void prePersist(){
		this.setCreatetime(new Date());
		this.setIfjiesuan(false);
		this.setJiesuanTuikuan(new BigDecimal(0));
		this.setWaimaiTuikuan(BigDecimal.ZERO);
		this.setBaoxianJiesuanTuikuan(BigDecimal.ZERO);
		this.setBaoxianWaimaiTuikuan(BigDecimal.ZERO);

		this.setGuideCheckStatus(0);
		if(this.getTip()==null) {
			this.setTip(BigDecimal.ZERO);
		}
		if(this.getStoreFanLi()==null) {
			this.setStoreFanLi(BigDecimal.ZERO);
		}
		setIsDivideStatistic(false);
	}
	
	@PreUpdate
	public void preUpdate(){
		this.setModifytime(new Date());
	}

	@Column(name="group_id")
	public Long getGroupId() {
		return groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	@Column(name="waimai_tuikuan", precision = 10)
	public BigDecimal getWaimaiTuikuan() {
		return waimaiTuikuan;
	}

	public void setWaimaiTuikuan(BigDecimal waimaiTuikuan) {
		this.waimaiTuikuan = waimaiTuikuan;
	}

	@Column(name="baoxian_jiesuan_tuikuan",precision=10)
	public BigDecimal getBaoxianJiesuanTuikuan() {
		return baoxianJiesuanTuikuan;
	}

	public void setBaoxianJiesuanTuikuan(BigDecimal baoxianJiesuanTuikuan) {
		this.baoxianJiesuanTuikuan = baoxianJiesuanTuikuan;
	}

	@Column(name="baoxian_waimai_tuikuan",precision=10)
	public BigDecimal getBaoxianWaimaiTuikuan() {
		return baoxianWaimaiTuikuan;
	}

	public void setBaoxianWaimaiTuikuan(BigDecimal baoxianWaimaiTuikuan) {
		this.baoxianWaimaiTuikuan = baoxianWaimaiTuikuan;
	}
	@Column(name = "insurance_order_download_url")
	public String getInsuranceOrderDownloadUrl() {
		return insuranceOrderDownloadUrl;
	}

	public void setInsuranceOrderDownloadUrl(String insuranceOrderDownloadUrl) {
		this.insuranceOrderDownloadUrl = insuranceOrderDownloadUrl;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="insurance")
	public Insurance getInsurance() {
		return insurance;
	}

	public void setInsurance(Insurance insurance) {
		this.insurance = insurance;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="supplier")
	public HyAdmin getSupplier() {
		return supplier;
	}

	public void setSupplier(HyAdmin supplier) {
		this.supplier = supplier;
	}

	@Column(name="guide_check_status")
	public Integer getGuideCheckStatus() {
		return guideCheckStatus;
	}

	public void setGuideCheckStatus(Integer guideCheckStatus) {
		this.guideCheckStatus = guideCheckStatus;
	}

	@Column(name="is_divide_statistic")
	public Boolean getIsDivideStatistic() {
		return isDivideStatistic;
	}

	public void setIsDivideStatistic(Boolean isDivideStatistic) {
		this.isDivideStatistic = isDivideStatistic;
	}

	@Column(name = "jiesuantime")
	public Date getJiesuantime() {
		return jiesuantime;
	}

	public void setJiesuantime(Date jiesuantime) {
		this.jiesuantime = jiesuantime;
	}

	@Column(name = "pay_time",length=19)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getPayTime() {
		return payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	@Column(name = "store_fan_li")
	public BigDecimal getStoreFanLi() {
		return storeFanLi;
	}

	public void setStoreFanLi(BigDecimal storeFanLi) {
		this.storeFanLi = storeFanLi;
	}
	
	@Column(name = "is_check_account")
	public Boolean getIsCheckAccount() {
		return isCheckAccount;
	}

	public void setIsCheckAccount(Boolean isCheckAccount) {
		this.isCheckAccount = isCheckAccount;
	}

}
