package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyPriceInfo generated by hbm2java
 */
@Entity
@Table(name = "hy_price_info")
public class HyPriceInfo implements java.io.Serializable {

	private long id;
	private Long ticket;
	private Long hotelroom;
	private Long hotelsceneRoom;
	private Date start;
	private Date end;
	private Long displayPrice;
	private Long sellPrice;
	private Long systemPrice;
	private Integer inventory;
	private Integer audit;

	public HyPriceInfo() {
	}

	public HyPriceInfo(long id) {
		this.id = id;
	}

	public HyPriceInfo(long id, Long ticket, Long hotelroom, Long hotelsceneRoom, Date start, Date end,
			Long displayPrice, Long sellPrice, Long systemPrice, Integer inventory, Integer audit) {
		this.id = id;
		this.ticket = ticket;
		this.hotelroom = hotelroom;
		this.hotelsceneRoom = hotelsceneRoom;
		this.start = start;
		this.end = end;
		this.displayPrice = displayPrice;
		this.sellPrice = sellPrice;
		this.systemPrice = systemPrice;
		this.inventory = inventory;
		this.audit = audit;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ticket")
	public Long getTicket() {
		return this.ticket;
	}

	public void setTicket(Long ticket) {
		this.ticket = ticket;
	}

	@Column(name = "hotelroom")
	public Long getHotelroom() {
		return this.hotelroom;
	}

	public void setHotelroom(Long hotelroom) {
		this.hotelroom = hotelroom;
	}

	@Column(name = "hotelscene_room")
	public Long getHotelsceneRoom() {
		return this.hotelsceneRoom;
	}

	public void setHotelsceneRoom(Long hotelsceneRoom) {
		this.hotelsceneRoom = hotelsceneRoom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start", length = 19)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end", length = 19)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column(name = "display_price", precision = 10, scale = 0)
	public Long getDisplayPrice() {
		return this.displayPrice;
	}

	public void setDisplayPrice(Long displayPrice) {
		this.displayPrice = displayPrice;
	}

	@Column(name = "sell_price", precision = 10, scale = 0)
	public Long getSellPrice() {
		return this.sellPrice;
	}

	public void setSellPrice(Long sellPrice) {
		this.sellPrice = sellPrice;
	}

	@Column(name = "system_price", precision = 10, scale = 0)
	public Long getSystemPrice() {
		return this.systemPrice;
	}

	public void setSystemPrice(Long systemPrice) {
		this.systemPrice = systemPrice;
	}

	@Column(name = "inventory")
	public Integer getInventory() {
		return this.inventory;
	}

	public void setInventory(Integer inventory) {
		this.inventory = inventory;
	}

	@Column(name = "audit")
	public Integer getAudit() {
		return this.audit;
	}

	public void setAudit(Integer audit) {
		this.audit = audit;
	}

}
