package com.hongyu.entity;
// default package
// Generated 2018-1-27 10:11:06 by Hibernate Tools 3.6.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HyPromotionPic generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler",
						"hyPromotion"
						})
@Table(name = "hy_promotion_pic")
public class HyPromotionPic implements java.io.Serializable {

	private Long id;
	private HyPromotion hyPromotion;
	private String sourcePath;
	private String largePath;
	private String mediumPath;
	private String thumbnailPath;
	private Boolean isTag;

	public HyPromotionPic() {
	}

	public HyPromotionPic(HyPromotion hyPromotion, String sourcePath, String largePath, String mediumPath,
			String thumbnailPath) {
		this.hyPromotion = hyPromotion;
		this.sourcePath = sourcePath;
		this.largePath = largePath;
		this.mediumPath = mediumPath;
		this.thumbnailPath = thumbnailPath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id")
	public HyPromotion getHyPromotion() {
		return this.hyPromotion;
	}

	public void setHyPromotion(HyPromotion hyPromotion) {
		this.hyPromotion = hyPromotion;
	}

	@Column(name = "source_path")
	public String getSourcePath() {
		return this.sourcePath;
	}

	public void setSourcePath(String sourcePath) {
		this.sourcePath = sourcePath;
	}

	@Column(name = "large_path")
	public String getLargePath() {
		return this.largePath;
	}

	public void setLargePath(String largePath) {
		this.largePath = largePath;
	}

	@Column(name = "medium_path")
	public String getMediumPath() {
		return this.mediumPath;
	}

	public void setMediumPath(String mediumPath) {
		this.mediumPath = mediumPath;
	}

	@Column(name = "thumbnail_path")
	public String getThumbnailPath() {
		return this.thumbnailPath;
	}

	public void setThumbnailPath(String thumbnailPath) {
		this.thumbnailPath = thumbnailPath;
	}

	public Boolean getIsTag() {
		return isTag;
	}

	public void setIsTag(Boolean isTag) {
		this.isTag = isTag;
	}

}
