package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HyScenicId generated by hbm2java
 */
@Embeddable
public class HyScenicId implements java.io.Serializable {

	private long id;
	private Long ticketSupplier;
	private Long creater;
	private String name;
	private Long area;
	private String address;
	private String star;
	private Date opentTime;
	private Date closeTime;
	private String exchangeAddress;

	public HyScenicId() {
	}

	public HyScenicId(long id) {
		this.id = id;
	}

	public HyScenicId(long id, Long ticketSupplier, Long creater, String name, Long area, String address, String star,
			Date opentTime, Date closeTime, String exchangeAddress) {
		this.id = id;
		this.ticketSupplier = ticketSupplier;
		this.creater = creater;
		this.name = name;
		this.area = area;
		this.address = address;
		this.star = star;
		this.opentTime = opentTime;
		this.closeTime = closeTime;
		this.exchangeAddress = exchangeAddress;
	}

	@Column(name = "ID", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ticket_supplier")
	public Long getTicketSupplier() {
		return this.ticketSupplier;
	}

	public void setTicketSupplier(Long ticketSupplier) {
		this.ticketSupplier = ticketSupplier;
	}

	@Column(name = "creater")
	public Long getCreater() {
		return this.creater;
	}

	public void setCreater(Long creater) {
		this.creater = creater;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "area")
	public Long getArea() {
		return this.area;
	}

	public void setArea(Long area) {
		this.area = area;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "star", length = 10)
	public String getStar() {
		return this.star;
	}

	public void setStar(String star) {
		this.star = star;
	}

	@Column(name = "opent_time", length = 8)
	public Date getOpentTime() {
		return this.opentTime;
	}

	public void setOpentTime(Date opentTime) {
		this.opentTime = opentTime;
	}

	@Column(name = "close_time", length = 8)
	public Date getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	@Column(name = "exchange_address")
	public String getExchangeAddress() {
		return this.exchangeAddress;
	}

	public void setExchangeAddress(String exchangeAddress) {
		this.exchangeAddress = exchangeAddress;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HyScenicId))
			return false;
		HyScenicId castOther = (HyScenicId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getTicketSupplier() == castOther.getTicketSupplier())
						|| (this.getTicketSupplier() != null && castOther.getTicketSupplier() != null
								&& this.getTicketSupplier().equals(castOther.getTicketSupplier())))
				&& ((this.getCreater() == castOther.getCreater()) || (this.getCreater() != null
						&& castOther.getCreater() != null && this.getCreater().equals(castOther.getCreater())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getArea() == castOther.getArea()) || (this.getArea() != null && castOther.getArea() != null
						&& this.getArea().equals(castOther.getArea())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& ((this.getStar() == castOther.getStar()) || (this.getStar() != null && castOther.getStar() != null
						&& this.getStar().equals(castOther.getStar())))
				&& ((this.getOpentTime() == castOther.getOpentTime()) || (this.getOpentTime() != null
						&& castOther.getOpentTime() != null && this.getOpentTime().equals(castOther.getOpentTime())))
				&& ((this.getCloseTime() == castOther.getCloseTime()) || (this.getCloseTime() != null
						&& castOther.getCloseTime() != null && this.getCloseTime().equals(castOther.getCloseTime())))
				&& ((this.getExchangeAddress() == castOther.getExchangeAddress())
						|| (this.getExchangeAddress() != null && castOther.getExchangeAddress() != null
								&& this.getExchangeAddress().equals(castOther.getExchangeAddress())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getTicketSupplier() == null ? 0 : this.getTicketSupplier().hashCode());
		result = 37 * result + (getCreater() == null ? 0 : this.getCreater().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getArea() == null ? 0 : this.getArea().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + (getStar() == null ? 0 : this.getStar().hashCode());
		result = 37 * result + (getOpentTime() == null ? 0 : this.getOpentTime().hashCode());
		result = 37 * result + (getCloseTime() == null ? 0 : this.getCloseTime().hashCode());
		result = 37 * result + (getExchangeAddress() == null ? 0 : this.getExchangeAddress().hashCode());
		return result;
	}

}
