package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HySceneHotel generated by hbm2java
 */
@Entity
@Table(name = "hy_scene_hotel")
public class HySceneHotel implements java.io.Serializable {

	private long id;
	private Long ticketSupplier;
	private Long creater;
	private String name;
	private String productId;
	private Long latestDate;
	private Long lowestPrice;
	private Boolean ifRealname;
	private Integer days;
	private String priceContain;
	private Integer reserveDays;
	private Date reserveTime;
	private String reserveKnow;
	private String refundKnow;
	private String sceneName;
	private String sceneStar;
	private Date sceneOpentime;
	private Date sceneClosetime;
	private String exchangeAddress;
	private Integer adults;
	private Integer childrens;
	private Integer students;
	private Integer olds;
	private String hotelName;
	private String hotelStar;
	private Long hotelArea;
	private String hotelAddress;
	private String audit;

	public HySceneHotel() {
	}

	public HySceneHotel(long id) {
		this.id = id;
	}

	public HySceneHotel(long id, Long ticketSupplier, Long creater, String name, String productId, Long latestDate,
			Long lowestPrice, Boolean ifRealname, Integer days, String priceContain, Integer reserveDays,
			Date reserveTime, String reserveKnow, String refundKnow, String sceneName, String sceneStar,
			Date sceneOpentime, Date sceneClosetime, String exchangeAddress, Integer adults, Integer childrens,
			Integer students, Integer olds, String hotelName, String hotelStar, Long hotelArea, String hotelAddress,
			String audit) {
		this.id = id;
		this.ticketSupplier = ticketSupplier;
		this.creater = creater;
		this.name = name;
		this.productId = productId;
		this.latestDate = latestDate;
		this.lowestPrice = lowestPrice;
		this.ifRealname = ifRealname;
		this.days = days;
		this.priceContain = priceContain;
		this.reserveDays = reserveDays;
		this.reserveTime = reserveTime;
		this.reserveKnow = reserveKnow;
		this.refundKnow = refundKnow;
		this.sceneName = sceneName;
		this.sceneStar = sceneStar;
		this.sceneOpentime = sceneOpentime;
		this.sceneClosetime = sceneClosetime;
		this.exchangeAddress = exchangeAddress;
		this.adults = adults;
		this.childrens = childrens;
		this.students = students;
		this.olds = olds;
		this.hotelName = hotelName;
		this.hotelStar = hotelStar;
		this.hotelArea = hotelArea;
		this.hotelAddress = hotelAddress;
		this.audit = audit;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ticket_supplier")
	public Long getTicketSupplier() {
		return this.ticketSupplier;
	}

	public void setTicketSupplier(Long ticketSupplier) {
		this.ticketSupplier = ticketSupplier;
	}

	@Column(name = "creater")
	public Long getCreater() {
		return this.creater;
	}

	public void setCreater(Long creater) {
		this.creater = creater;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "product_id")
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "latest_date", precision = 10, scale = 0)
	public Long getLatestDate() {
		return this.latestDate;
	}

	public void setLatestDate(Long latestDate) {
		this.latestDate = latestDate;
	}

	@Column(name = "lowest_price", precision = 10, scale = 0)
	public Long getLowestPrice() {
		return this.lowestPrice;
	}

	public void setLowestPrice(Long lowestPrice) {
		this.lowestPrice = lowestPrice;
	}

	@Column(name = "if_realname")
	public Boolean getIfRealname() {
		return this.ifRealname;
	}

	public void setIfRealname(Boolean ifRealname) {
		this.ifRealname = ifRealname;
	}

	@Column(name = "days")
	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	@Column(name = "price_contain")
	public String getPriceContain() {
		return this.priceContain;
	}

	public void setPriceContain(String priceContain) {
		this.priceContain = priceContain;
	}

	@Column(name = "reserve_days")
	public Integer getReserveDays() {
		return this.reserveDays;
	}

	public void setReserveDays(Integer reserveDays) {
		this.reserveDays = reserveDays;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "reserve_time", length = 8)
	public Date getReserveTime() {
		return this.reserveTime;
	}

	public void setReserveTime(Date reserveTime) {
		this.reserveTime = reserveTime;
	}

	@Column(name = "reserve_know")
	public String getReserveKnow() {
		return this.reserveKnow;
	}

	public void setReserveKnow(String reserveKnow) {
		this.reserveKnow = reserveKnow;
	}

	@Column(name = "refund_know")
	public String getRefundKnow() {
		return this.refundKnow;
	}

	public void setRefundKnow(String refundKnow) {
		this.refundKnow = refundKnow;
	}

	@Column(name = "scene_name")
	public String getSceneName() {
		return this.sceneName;
	}

	public void setSceneName(String sceneName) {
		this.sceneName = sceneName;
	}

	@Column(name = "scene_star")
	public String getSceneStar() {
		return this.sceneStar;
	}

	public void setSceneStar(String sceneStar) {
		this.sceneStar = sceneStar;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "scene_opentime", length = 8)
	public Date getSceneOpentime() {
		return this.sceneOpentime;
	}

	public void setSceneOpentime(Date sceneOpentime) {
		this.sceneOpentime = sceneOpentime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "scene_closetime", length = 8)
	public Date getSceneClosetime() {
		return this.sceneClosetime;
	}

	public void setSceneClosetime(Date sceneClosetime) {
		this.sceneClosetime = sceneClosetime;
	}

	@Column(name = "exchange_address")
	public String getExchangeAddress() {
		return this.exchangeAddress;
	}

	public void setExchangeAddress(String exchangeAddress) {
		this.exchangeAddress = exchangeAddress;
	}

	@Column(name = "adults")
	public Integer getAdults() {
		return this.adults;
	}

	public void setAdults(Integer adults) {
		this.adults = adults;
	}

	@Column(name = "childrens")
	public Integer getChildrens() {
		return this.childrens;
	}

	public void setChildrens(Integer childrens) {
		this.childrens = childrens;
	}

	@Column(name = "students")
	public Integer getStudents() {
		return this.students;
	}

	public void setStudents(Integer students) {
		this.students = students;
	}

	@Column(name = "olds")
	public Integer getOlds() {
		return this.olds;
	}

	public void setOlds(Integer olds) {
		this.olds = olds;
	}

	@Column(name = "hotel_name")
	public String getHotelName() {
		return this.hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	@Column(name = "hotel_star")
	public String getHotelStar() {
		return this.hotelStar;
	}

	public void setHotelStar(String hotelStar) {
		this.hotelStar = hotelStar;
	}

	@Column(name = "hotel_area")
	public Long getHotelArea() {
		return this.hotelArea;
	}

	public void setHotelArea(Long hotelArea) {
		this.hotelArea = hotelArea;
	}

	@Column(name = "hotel_address")
	public String getHotelAddress() {
		return this.hotelAddress;
	}

	public void setHotelAddress(String hotelAddress) {
		this.hotelAddress = hotelAddress;
	}

	@Column(name = "audit", length = 11)
	public String getAudit() {
		return this.audit;
	}

	public void setAudit(String audit) {
		this.audit = audit;
	}

}
