package com.hongyu.entity;
// default package
// Generated 2018-1-12 17:38:27 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Digits;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.hongyu.util.Constants.DeductPiaowu;

/**
 * HySupplierDeductQianzheng generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler", 
						"supplierContracts"})
@Table(name = "hy_supplier_deduct_qianzheng")
public class HySupplierDeductQianzheng implements java.io.Serializable {

	private Long id;
	private DeductPiaowu deductQianzheng;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal rentouQianzheng;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal liushuiQianzheng;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "deduct_qianzheng", nullable = false)
	public DeductPiaowu getDeductQianzheng() {
		return this.deductQianzheng;
	}

	public void setDeductQianzheng(DeductPiaowu deductQianzheng) {
		this.deductQianzheng = deductQianzheng;
	}

	@Column(name = "rentou_qianzheng", precision = 10, scale = 0)
	public BigDecimal getRentouQianzheng() {
		return this.rentouQianzheng;
	}

	public void setRentouQianzheng(BigDecimal rentouQianzheng) {
		this.rentouQianzheng = rentouQianzheng;
	}

	@Column(name = "liushui_qianzheng", precision = 10, scale = 0)
	public BigDecimal getLiushuiQianzheng() {
		return this.liushuiQianzheng;
	}

	public void setLiushuiQianzheng(BigDecimal liushuiQianzheng) {
		this.liushuiQianzheng = liushuiQianzheng;
	}

}
