package com.hongyu.entity;
// default package
// Generated 2018-1-12 17:38:27 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Digits;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.hongyu.util.Constants.DeductPiaowu;

/**
 * HySupplierDeductRengou generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "hy_supplier_deduct_rengou")
public class HySupplierDeductRengou implements java.io.Serializable {

	private Long id;
	private DeductPiaowu deductRengou;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal rentouRengou;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal liushuiRengou;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "deduct_rengou", nullable = false)
	public DeductPiaowu getDeductRengou() {
		return this.deductRengou;
	}

	public void setDeductRengou(DeductPiaowu deductRengou) {
		this.deductRengou = deductRengou;
	}

	@Column(name = "rentou_rengou", precision = 10, scale = 0)
	public BigDecimal getRentouRengou() {
		return this.rentouRengou;
	}

	public void setRentouRengou(BigDecimal rentouRengou) {
		this.rentouRengou = rentouRengou;
	}

	@Column(name = "liushui_rengou", precision = 10, scale = 0)
	public BigDecimal getLiushuiRengou() {
		return this.liushuiRengou;
	}

	public void setLiushuiRengou(BigDecimal liushuiRengou) {
		this.liushuiRengou = liushuiRengou;
	}

}
