package com.hongyu.entity;
// default package
// Generated 2018-1-12 17:38:27 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Digits;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.hongyu.util.Constants.DeductLine;

/**
 * HySupplierDeductQiche generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "hy_supplier_deduct_qiche")
public class HySupplierDeductQiche implements java.io.Serializable {

	private Long id;
	private DeductLine deductQiche;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal tuankeQiche;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal sankeQiche;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal rentouQiche;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "deduct_qiche", nullable = false)
	public DeductLine getDeductQiche() {
		return this.deductQiche;
	}

	public void setDeductQiche(DeductLine deductQiche) {
		this.deductQiche = deductQiche;
	}

	@Column(name = "tuanke_qiche", precision = 10, scale = 0)
	public BigDecimal getTuankeQiche() {
		return this.tuankeQiche;
	}

	public void setTuankeQiche(BigDecimal tuankeQiche) {
		this.tuankeQiche = tuankeQiche;
	}

	@Column(name = "sanke_qiche", precision = 10, scale = 0)
	public BigDecimal getSankeQiche() {
		return this.sankeQiche;
	}

	public void setSankeQiche(BigDecimal sankeQiche) {
		this.sankeQiche = sankeQiche;
	}

	@Column(name = "rentou_qiche", precision = 10, scale = 0)
	public BigDecimal getRentouQiche() {
		return this.rentouQiche;
	}

	public void setRentouQiche(BigDecimal rentouQiche) {
		this.rentouQiche = rentouQiche;
	}

}
