package com.hongyu.entity;
// default package
// Generated 2018-1-12 17:38:27 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Digits;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.hongyu.util.Constants.DeductPiaowu;

/**
 * HySupplierDeductPiaowu generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "hy_supplier_deduct_piaowu")
public class HySupplierDeductPiaowu implements java.io.Serializable {

	private Long id;
	private DeductPiaowu deductPiaowu;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal rentouPiaowu;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal liushuiPiaowu;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "deduct_piaowu", nullable = false)
	public DeductPiaowu getDeductPiaowu() {
		return this.deductPiaowu;
	}

	public void setDeductPiaowu(DeductPiaowu deductPiaowu) {
		this.deductPiaowu = deductPiaowu;
	}

	@Column(name = "rentou", precision = 10, scale = 0)
	public BigDecimal getRentouPiaowu() {
		return this.rentouPiaowu;
	}

	public void setRentouPiaowu(BigDecimal rentou) {
		this.rentouPiaowu = rentou;
	}

	@Column(name = "liushui", precision = 10, scale = 0)
	public BigDecimal getLiushuiPiaowu() {
		return this.liushuiPiaowu;
	}

	public void setLiushuiPiaowu(BigDecimal liushui) {
		this.liushuiPiaowu = liushui;
	}

}
