package com.hongyu.entity;
// default package
// Generated 2018-1-12 17:38:27 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Digits;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.hongyu.util.Constants.DeductLine;

/**
 * HySupplierDeductChujing generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "hy_supplier_deduct_chujing")
public class HySupplierDeductChujing implements java.io.Serializable {


	private Long id;
	private DeductLine deductChujing;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal sankeChujing;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal tuankeChujing;
	
	@Digits(integer=10, fraction=2)
	private BigDecimal rentouChujing;


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "deduct_chujing", nullable = false)
	public DeductLine getDeductChujing() {
		return this.deductChujing;
	}

	public void setDeductChujing(DeductLine deductChujing) {
		this.deductChujing = deductChujing;
	}

	@Column(name = "sanke_chujing", precision = 10, scale = 0)
	public BigDecimal getSankeChujing() {
		return this.sankeChujing;
	}

	public void setSankeChujing(BigDecimal sankeChujing) {
		this.sankeChujing = sankeChujing;
	}

	@Column(name = "tuanke_chujing", precision = 10, scale = 0)
	public BigDecimal getTuankeChujing() {
		return this.tuankeChujing;
	}

	public void setTuankeChujing(BigDecimal tuankeChujing) {
		this.tuankeChujing = tuankeChujing;
	}

	@Column(name = "rentou_chujing", precision = 10, scale = 0)
	public BigDecimal getRentouChujing() {
		return this.rentouChujing;
	}

	public void setRentouChujing(BigDecimal rentouChujing) {
		this.rentouChujing = rentouChujing;
	}

}
