package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyTicketSupplierPay generated by hbm2java
 */
@Entity
@Table(name = "hy_ticket_supplier_pay")
public class HyTicketSupplierPay implements java.io.Serializable {

	private long id;
	private Long ticketSupplier;
	private Long money;
	private Date start;
	private Date end;
	private String remark;
	private String audit;
	private String payStatus;

	public HyTicketSupplierPay() {
	}

	public HyTicketSupplierPay(long id) {
		this.id = id;
	}

	public HyTicketSupplierPay(long id, Long ticketSupplier, Long money, Date start, Date end, String remark,
			String audit, String payStatus) {
		this.id = id;
		this.ticketSupplier = ticketSupplier;
		this.money = money;
		this.start = start;
		this.end = end;
		this.remark = remark;
		this.audit = audit;
		this.payStatus = payStatus;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ticket_supplier")
	public Long getTicketSupplier() {
		return this.ticketSupplier;
	}

	public void setTicketSupplier(Long ticketSupplier) {
		this.ticketSupplier = ticketSupplier;
	}

	@Column(name = "money", precision = 10, scale = 0)
	public Long getMoney() {
		return this.money;
	}

	public void setMoney(Long money) {
		this.money = money;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start", length = 19)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end", length = 19)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "audit")
	public String getAudit() {
		return this.audit;
	}

	public void setAudit(String audit) {
		this.audit = audit;
	}

	@Column(name = "pay_status")
	public String getPayStatus() {
		return this.payStatus;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

}
