package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyTicketSupplier generated by hbm2java
 */
@Entity
@Table(name = "hy_ticket_supplier")
public class HyTicketSupplier implements java.io.Serializable {

	private long id;
	private String name;
	private Date startTime;
	private Date endTime;
	private Long creater;
	private Long area;
	private String address;
	private String signPeople;
	private Boolean signContract;
	private String contractNo;
	private String description;
	private String adminName;
	private String telephone;
	private Long bank;
	private String remark;

	public HyTicketSupplier() {
	}

	public HyTicketSupplier(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public HyTicketSupplier(long id, String name, Date startTime, Date endTime, Long creater, Long area, String address,
			String signPeople, Boolean signContract, String contractNo, String description, String adminName,
			String telephone, Long bank, String remark) {
		this.id = id;
		this.name = name;
		this.startTime = startTime;
		this.endTime = endTime;
		this.creater = creater;
		this.area = area;
		this.address = address;
		this.signPeople = signPeople;
		this.signContract = signContract;
		this.contractNo = contractNo;
		this.description = description;
		this.adminName = adminName;
		this.telephone = telephone;
		this.bank = bank;
		this.remark = remark;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "creater")
	public Long getCreater() {
		return this.creater;
	}

	public void setCreater(Long creater) {
		this.creater = creater;
	}

	@Column(name = "area")
	public Long getArea() {
		return this.area;
	}

	public void setArea(Long area) {
		this.area = area;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "sign_people", length = 50)
	public String getSignPeople() {
		return this.signPeople;
	}

	public void setSignPeople(String signPeople) {
		this.signPeople = signPeople;
	}

	@Column(name = "sign_contract")
	public Boolean getSignContract() {
		return this.signContract;
	}

	public void setSignContract(Boolean signContract) {
		this.signContract = signContract;
	}

	@Column(name = "contract_no")
	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "admin_name", length = 10)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "telephone", length = 30)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "bank")
	public Long getBank() {
		return this.bank;
	}

	public void setBank(Long bank) {
		this.bank = bank;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
