package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyTicketSupplierPayDetail generated by hbm2java
 */
@Entity
@Table(name = "hy_ticket_supplier_pay_detail")
public class HyTicketSupplierPayDetail implements java.io.Serializable {

	private long id;
	private Long supplierPay;
	private Long payType;
	private Long money;
	private Date time;

	public HyTicketSupplierPayDetail() {
	}

	public HyTicketSupplierPayDetail(long id) {
		this.id = id;
	}

	public HyTicketSupplierPayDetail(long id, Long supplierPay, Long payType, Long money, Date time) {
		this.id = id;
		this.supplierPay = supplierPay;
		this.payType = payType;
		this.money = money;
		this.time = time;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "supplier_pay")
	public Long getSupplierPay() {
		return this.supplierPay;
	}

	public void setSupplierPay(Long supplierPay) {
		this.supplierPay = supplierPay;
	}

	@Column(name = "pay_type")
	public Long getPayType() {
		return this.payType;
	}

	public void setPayType(Long payType) {
		this.payType = payType;
	}

	@Column(name = "money", precision = 10, scale = 0)
	public Long getMoney() {
		return this.money;
	}

	public void setMoney(Long money) {
		this.money = money;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
