package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyTradeRecord generated by hbm2java
 */
@Entity
@Table(name = "hy_trade_record")
public class HyTradeRecord implements java.io.Serializable {

	private long id;
	private Long distributor;
	private Date tradeDate;
	private Integer abstract_;
	private Long payType;
	private Long money;
	private Long balance;

	public HyTradeRecord() {
	}

	public HyTradeRecord(long id) {
		this.id = id;
	}

	public HyTradeRecord(long id, Long distributor, Date tradeDate, Integer abstract_, Long payType, Long money,
			Long balance) {
		this.id = id;
		this.distributor = distributor;
		this.tradeDate = tradeDate;
		this.abstract_ = abstract_;
		this.payType = payType;
		this.money = money;
		this.balance = balance;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "distributor")
	public Long getDistributor() {
		return this.distributor;
	}

	public void setDistributor(Long distributor) {
		this.distributor = distributor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "trade_date", length = 19)
	public Date getTradeDate() {
		return this.tradeDate;
	}

	public void setTradeDate(Date tradeDate) {
		this.tradeDate = tradeDate;
	}

	@Column(name = "abstract")
	public Integer getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(Integer abstract_) {
		this.abstract_ = abstract_;
	}

	@Column(name = "pay_type")
	public Long getPayType() {
		return this.payType;
	}

	public void setPayType(Long payType) {
		this.payType = payType;
	}

	@Column(name = "money", precision = 10, scale = 0)
	public Long getMoney() {
		return this.money;
	}

	public void setMoney(Long money) {
		this.money = money;
	}

	@Column(name = "balance", precision = 10, scale = 0)
	public Long getBalance() {
		return this.balance;
	}

	public void setBalance(Long balance) {
		this.balance = balance;
	}

}
