package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.hongyu.util.Constants.AuditStatus;

/**
 * HyVisa generated by hbm2java
 */
@Entity
@Table(name = "hy_visa")
public class HyVisa implements Serializable {
	private Long id;//ID 
	private HyAdmin creator;
	private String productId; //产品ID
	private String productName;
	@JsonIgnore
	private HySupplier ticketSupplier;
	@JsonIgnore
	private HyCountry country; //目的地
	private Integer visaType;  //1-个人旅游,2-商务签证
	private String duration; //办理时长
	private String times; //入境次数
	private Boolean isInterview; //True-需要面试,false-无需面试
	private String stayDays;  //可停留天数
	private String expireDays; //签证有效期(20190106删去该字段)
	private String serviceContent; //服务内容
	private String priceContain;  //费用包含
	private String reserveRequirement; //预定须知
	private Date createTime;
	private Date modifyTime;
	private Date submitTime; //提交申请时间
	@JsonIgnore
	private HyAdmin submitter; //申请人
	private Integer auditStatus; //1-未提交,2-已提交,审核中,3-审核通过,4-驳回
	private Integer saleStatus; //1-未上架,2-已上架,3-已下架
	private String processInstanceId; //流程实例id
	private Boolean status; //true-正常,false-取消
	private String accessory; //上传附件
	private String introduce; //材料介绍
	private String introduction; //产品介绍,附文本;用逗号分开产品文件url
	private String ticketFile; ////票务推广文件
	private HyPromotionActivity hyPromotionActivity; //促销
	/*签证价格列表*/
	private List<HyVisaPrices> hyVisaPrices=new ArrayList<>();
	
	//以下为门户用字段
	private Integer mhState; //门户完善状态,0未完善,1已完善,2供应商有修改,待完善
	private String mhProductName; //门户用产品名称
	private String mhPriceContain; //门户用费用包含
	private String mhReserveRequirement; //门户用预订须知
	private String mhAcceptScope; //门户用签证受理范围
	private String mhAttention; //签证注意事项
	private Integer mhIsSale; //门户是否上线,0下线,1上线
	private Date mhCreateTime; //完善时间
	private Date mhUpdateTime; //最后修改时间
	private String mhOperator; //完善人
	private Integer mhIsHot; //是否热门国家,0否,1是
	
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "creator")
	public HyAdmin getCreator() {
		return this.creator;
	}
	public void setCreator(HyAdmin creator) {
		this.creator = creator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "submitter")
	public HyAdmin getSubmitter() {
		return submitter;
	}
	public void setSubmitter(HyAdmin submitter) {
		this.submitter = submitter;
	}
	
	@Column(name = "product_id")
	public String getProductId() {
		return this.productId;
	}
	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country")
	public HyCountry getCountry() {
		return this.country;
	}
	public void setCountry(HyCountry country) {
		this.country = country;
	}

	@Column(name = "visa_type")
	public Integer getVisaType() {
		return this.visaType;
	}
	public void setVisaType(Integer visaType) {
		this.visaType = visaType;
	}

	@Column(name = "duration")
	public String getDuration() {
		return this.duration;
	}
	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "times")
	public String getTimes() {
		return this.times;
	}
	public void setTimes(String times) {
		this.times = times;
	}

	@Column(name = "is_interview")
	public Boolean getIsInterview() {
		return this.isInterview;
	}
	public void setIsInterview(Boolean isInterview) {
		this.isInterview = isInterview;
	}

	@Column(name = "stay_days")
	public String getStayDays() {
		return this.stayDays;
	}
	public void setStayDays(String stayDays) {
		this.stayDays = stayDays;
	}

	@Column(name = "expire_days")
	public String getExpireDays() {
		return this.expireDays;
	}
	public void setExpireDays(String expireDays) {
		this.expireDays = expireDays;
	}

	@Column(name = "service_content")
	public String getServiceContent() {
		return this.serviceContent;
	}
	public void setServiceContent(String serviceContent) {
		this.serviceContent = serviceContent;
	}

	@Column(name = "price_contain")
	public String getPriceContain() {
		return this.priceContain;
	}
	public void setPriceContain(String priceContain) {
		this.priceContain = priceContain;
	}

	@Column(name = "reserve_requirement")
	public String getReserveRequirement() {
		return this.reserveRequirement;
	}

	public void setReserveRequirement(String reserveRequirement) {
		this.reserveRequirement = reserveRequirement;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time",length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getModifyTime() {
		return modifyTime;
	}
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "apply_time", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getSubmitTime() {
		return submitTime;
	}
	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	@Column(name="audit_status")
	public Integer getAuditStatus() {
		return auditStatus;
	}
	public void setAuditStatus(Integer auditStatus) {
		this.auditStatus = auditStatus;
	}

	@Column(name="sale_status")
	public Integer getSaleStatus() {
		return saleStatus;
	}
	public void setSaleStatus(Integer saleStatus) {
		this.saleStatus = saleStatus;
	}

	@Column(name="process_instance_id")
	public String getProcessInstanceId() {
		return processInstanceId;
	}
	public void setProcessInstanceId(String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id")
	public HySupplier getTicketSupplier() {
		return ticketSupplier;
	}
	public void setTicketSupplier(HySupplier ticketSupplier) {
		this.ticketSupplier = ticketSupplier;
	}

	@Column(name="status")
	public Boolean getStatus() {
		return status;
	}
	public void setStatus(Boolean status) {
		this.status = status;
	}
	
	@Column(name="accessory")
	public String getAccessory() {
		return accessory;
	}
	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}
	
	@Column(name="introduce")
	public String getIntroduce() {
		return introduce;
	}
	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}
	
	@Column(name="introduction")
	public String getIntroduction() {
		return introduction;
	}
	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}
	
	@Column(name="ticket_file")
	public String getTicketFile() {
		return ticketFile;
	}
	public void setTicketFile(String ticketFile) {
		this.ticketFile = ticketFile;
	}
	
	@JsonProperty
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyVisa")
	public List<HyVisaPrices> getHyVisaPrices() {
		return hyVisaPrices;
	}
	public void setHyVisaPrices(List<HyVisaPrices> hyVisaPrices) {
		this.hyVisaPrices = hyVisaPrices;
	}
		
	@ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
	@JoinColumn(name="promotion_id")
	public HyPromotionActivity getHyPromotionActivity() {
		return hyPromotionActivity;
	}
	public void setHyPromotionActivity(HyPromotionActivity hyPromotionActivity) {
		this.hyPromotionActivity = hyPromotionActivity;
	}
	
	@Column(name="mh_state")
	public Integer getMhState() {
		return mhState;
	}
	public void setMhState(Integer mhState) {
		this.mhState = mhState;
	}
	
	@Column(name="mh_product_name")
	public String getMhProductName() {
		return mhProductName;
	}
	public void setMhProductName(String mhProductName) {
		this.mhProductName = mhProductName;
	}
	
	@Column(name="mh_price_contain")
	public String getMhPriceContain() {
		return mhPriceContain;
	}
	public void setMhPriceContain(String mhPriceContain) {
		this.mhPriceContain = mhPriceContain;
	}
	
	@Column(name="mh_reserve_requirement")
	public String getMhReserveRequirement() {
		return mhReserveRequirement;
	}
	public void setMhReserveRequirement(String mhReserveRequirement) {
		this.mhReserveRequirement = mhReserveRequirement;
	}
	
	@Column(name="mh_accept_scope")
	public String getMhAcceptScope() {
		return mhAcceptScope;
	}
	public void setMhAcceptScope(String mhAcceptScope) {
		this.mhAcceptScope = mhAcceptScope;
	}
	
	@Column(name="mh_attention")
	public String getMhAttention() {
		return mhAttention;
	}
	public void setMhAttention(String mhAttention) {
		this.mhAttention = mhAttention;
	}
	
	@Column(name="mh_is_sale")
	public Integer getMhIsSale() {
		return mhIsSale;
	}
	public void setMhIsSale(Integer mhIsSale) {
		this.mhIsSale = mhIsSale;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mh_create_time", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getMhCreateTime() {
		return mhCreateTime;
	}
	public void setMhCreateTime(Date mhCreateTime) {
		this.mhCreateTime = mhCreateTime;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mh_update_time", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getMhUpdateTime() {
		return mhUpdateTime;
	}
	public void setMhUpdateTime(Date mhUpdateTime) {
		this.mhUpdateTime = mhUpdateTime;
	}
	
	@Column(name="mh_operator")
	public String getMhOperator() {
		return mhOperator;
	}
	public void setMhOperator(String mhOperator) {
		this.mhOperator = mhOperator;
	}
	
	@Column(name="mh_is_hot")
	public Integer getMhIsHot() {
		return mhIsHot;
	}
	public void setMhIsHot(Integer mhIsHot) {
		this.mhIsHot = mhIsHot;
	}
	
	@PrePersist
	public void prePersist(){
		this.setMhState(0); 
		this.setMhIsSale(0);
	}
}
