package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HyWorkflowType generated by hbm2java
 */
@Entity
@Table(name = "hy_workflow_type")
public class HyWorkflowType implements java.io.Serializable {

	private long id;
	private String name;
	private Set<HyWorkflowModel> hyWorkflowModels = new HashSet<HyWorkflowModel>(0);

	public HyWorkflowType() {
	}

	public HyWorkflowType(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public HyWorkflowType(long id, String name, Set<HyWorkflowModel> hyWorkflowModels) {
		this.id = id;
		this.name = name;
		this.hyWorkflowModels = hyWorkflowModels;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyWorkflowType")
	public Set<HyWorkflowModel> getHyWorkflowModels() {
		return this.hyWorkflowModels;
	}

	public void setHyWorkflowModels(Set<HyWorkflowModel> hyWorkflowModels) {
		this.hyWorkflowModels = hyWorkflowModels;
	}

}
