package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HyWorkflowModel generated by hbm2java
 */
@Entity
@Table(name = "hy_workflow_model")
public class HyWorkflowModel implements java.io.Serializable {

	private long id;
	private HyWorkflowType hyWorkflowType;
	private String tableName;
	private String url;
	private String name;
	private String description;
	private Integer order;
	private Set<HyTodoWork> hyTodoWorks = new HashSet<HyTodoWork>(0);
	private Set<HyWorkflowStepModel> hyWorkflowStepModels = new HashSet<HyWorkflowStepModel>(0);

	public HyWorkflowModel() {
	}

	public HyWorkflowModel(long id, HyWorkflowType hyWorkflowType, String tableName, String name) {
		this.id = id;
		this.hyWorkflowType = hyWorkflowType;
		this.tableName = tableName;
		this.name = name;
	}

	public HyWorkflowModel(long id, HyWorkflowType hyWorkflowType, String tableName, String url, String name,
			String description, Integer order, Set<HyTodoWork> hyTodoWorks,
			Set<HyWorkflowStepModel> hyWorkflowStepModels) {
		this.id = id;
		this.hyWorkflowType = hyWorkflowType;
		this.tableName = tableName;
		this.url = url;
		this.name = name;
		this.description = description;
		this.order = order;
		this.hyTodoWorks = hyTodoWorks;
		this.hyWorkflowStepModels = hyWorkflowStepModels;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flow_type", nullable = false)
	public HyWorkflowType getHyWorkflowType() {
		return this.hyWorkflowType;
	}

	public void setHyWorkflowType(HyWorkflowType hyWorkflowType) {
		this.hyWorkflowType = hyWorkflowType;
	}

	@Column(name = "table_name", nullable = false)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "order")
	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyWorkflowModel")
	public Set<HyTodoWork> getHyTodoWorks() {
		return this.hyTodoWorks;
	}

	public void setHyTodoWorks(Set<HyTodoWork> hyTodoWorks) {
		this.hyTodoWorks = hyTodoWorks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyWorkflowModel")
	public Set<HyWorkflowStepModel> getHyWorkflowStepModels() {
		return this.hyWorkflowStepModels;
	}

	public void setHyWorkflowStepModels(Set<HyWorkflowStepModel> hyWorkflowStepModels) {
		this.hyWorkflowStepModels = hyWorkflowStepModels;
	}

}
