package com.hongyu.entity;
// Generated 2017-12-24 21:20:19 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HyWorkflowStepModel generated by hbm2java
 */
@Entity
@Table(name = "hy_workflow_step_model")
public class HyWorkflowStepModel implements java.io.Serializable {

	private long id;
	private HyWorkflowModel hyWorkflowModel;
	private int sequence;
	private String name;
	private String remark;
	private long departmentModel;
	private boolean hasChecked;
	private boolean isChecked;
	private Set<HyTodoWork> hyTodoWorks = new HashSet<HyTodoWork>(0);

	public HyWorkflowStepModel() {
	}

	public HyWorkflowStepModel(long id, HyWorkflowModel hyWorkflowModel, int sequence, String name,
			long departmentModel, boolean hasChecked, boolean isChecked) {
		this.id = id;
		this.hyWorkflowModel = hyWorkflowModel;
		this.sequence = sequence;
		this.name = name;
		this.departmentModel = departmentModel;
		this.hasChecked = hasChecked;
		this.isChecked = isChecked;
	}

	public HyWorkflowStepModel(long id, HyWorkflowModel hyWorkflowModel, int sequence, String name, String remark,
			long departmentModel, boolean hasChecked, boolean isChecked, Set<HyTodoWork> hyTodoWorks) {
		this.id = id;
		this.hyWorkflowModel = hyWorkflowModel;
		this.sequence = sequence;
		this.name = name;
		this.remark = remark;
		this.departmentModel = departmentModel;
		this.hasChecked = hasChecked;
		this.isChecked = isChecked;
		this.hyTodoWorks = hyTodoWorks;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workflow_id", nullable = false)
	public HyWorkflowModel getHyWorkflowModel() {
		return this.hyWorkflowModel;
	}

	public void setHyWorkflowModel(HyWorkflowModel hyWorkflowModel) {
		this.hyWorkflowModel = hyWorkflowModel;
	}

	@Column(name = "sequence", nullable = false)
	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "department_model", nullable = false)
	public long getDepartmentModel() {
		return this.departmentModel;
	}

	public void setDepartmentModel(long departmentModel) {
		this.departmentModel = departmentModel;
	}

	@Column(name = "has_checked", nullable = false)
	public boolean isHasChecked() {
		return this.hasChecked;
	}

	public void setHasChecked(boolean hasChecked) {
		this.hasChecked = hasChecked;
	}

	@Column(name = "is_checked", nullable = false)
	public boolean isIsChecked() {
		return this.isChecked;
	}

	public void setIsChecked(boolean isChecked) {
		this.isChecked = isChecked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyWorkflowStepModel")
	public Set<HyTodoWork> getHyTodoWorks() {
		return this.hyTodoWorks;
	}

	public void setHyTodoWorks(Set<HyTodoWork> hyTodoWorks) {
		this.hyTodoWorks = hyTodoWorks;
	}

}
