package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyInsuranceAttach generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_insurance_attach")
public class InsuranceAttach implements java.io.Serializable {

	private Long id;
	private Date createDate;
	private Date modifyDate;
	private String securityProject;
	private String applicableTerms;
	private BigDecimal insuranceContent;
	private String insuranceMoney;
	private Integer orders;

	private Insurance insurance;

	

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "security_project")
	public String getSecurityProject() {
		return this.securityProject;
	}

	public void setSecurityProject(String securityProject) {
		this.securityProject = securityProject;
	}

	@Column(name = "applicable_terms")
	public String getApplicableTerms() {
		return this.applicableTerms;
	}

	public void setApplicableTerms(String applicableTerms) {
		this.applicableTerms = applicableTerms;
	}

	@Column(name = "insurance_content", precision = 10)
	public BigDecimal getInsuranceContent() {
		return this.insuranceContent;
	}

	public void setInsuranceContent(BigDecimal insuranceContent) {
		this.insuranceContent = insuranceContent;
	}
	@Column(name="insurance_money")
	public String getInsuranceMoney() {
		return insuranceMoney;
	}

	public void setInsuranceMoney(String insuranceMoney) {
		this.insuranceMoney = insuranceMoney;
	}

	@Column(name = "orders")
	public Integer getOrders() {
		return this.orders;
	}

	public void setOrders(Integer orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch=FetchType.LAZY, cascade = CascadeType.REFRESH,optional = false)
	@JoinColumn(name="insurance_id")
	@JsonIgnore
	public Insurance getInsurance() {
		return insurance;
	}

	public void setInsurance(Insurance insurance) {
		this.insurance = insurance;
	}
	@PrePersist
	public void prePersist(){
		this.setCreateDate(new Date());
	}
	@PreUpdate
	public void preUpdate(){
		this.setModifyDate(new Date());
	}

}
