package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HyInsuranceMonth generated by hbm2java
 */
@Entity
@Table(name = "hy_insurance_month")
public class InsuranceMonth implements java.io.Serializable {

	private Long id;
	private Date beginDate;
	private Date endDate;
	private BigDecimal groupReceived;
	private BigDecimal zizhuReceived;
	private BigDecimal totalReceived;
	private BigDecimal totalShifu;
	private BigDecimal totalProfit;

	public InsuranceMonth() {
	}

	public InsuranceMonth(Long id) {
		this.id = id;
	}
	public InsuranceMonth(Long id, Date beginDate, Date endDate,
			BigDecimal groupReceived, BigDecimal zizhuReceived,
			BigDecimal totalReceived, BigDecimal totalShifu,
			BigDecimal totalProfit) {
		this.id = id;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.groupReceived = groupReceived;
		this.zizhuReceived = zizhuReceived;
		this.totalReceived = totalReceived;
		this.totalShifu = totalShifu;
		this.totalProfit = totalProfit;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "begin_date", length = 10)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "group_received", precision = 10)
	public BigDecimal getGroupReceived() {
		return this.groupReceived;
	}

	public void setGroupReceived(BigDecimal groupReceived) {
		this.groupReceived = groupReceived;
	}

	@Column(name = "zizhu_received", precision = 10)
	public BigDecimal getZizhuReceived() {
		return this.zizhuReceived;
	}

	public void setZizhuReceived(BigDecimal zizhuReceived) {
		this.zizhuReceived = zizhuReceived;
	}

	@Column(name = "total_received", precision = 10)
	public BigDecimal getTotalReceived() {
		return this.totalReceived;
	}

	public void setTotalReceived(BigDecimal totalReceived) {
		this.totalReceived = totalReceived;
	}

	@Column(name = "total_shifu", precision = 10)
	public BigDecimal getTotalShifu() {
		return this.totalShifu;
	}

	public void setTotalShifu(BigDecimal totalShifu) {
		this.totalShifu = totalShifu;
	}

	@Column(name = "total_profit", precision = 10)
	public BigDecimal getTotalProfit() {
		return this.totalProfit;
	}

	public void setTotalProfit(BigDecimal totalProfit) {
		this.totalProfit = totalProfit;
	}

}
