package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyInsuranceTimes generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_insurance_times")
public class InsuranceTime implements java.io.Serializable {

	private Long id;
	private Integer ageStart;
	private Integer ageEnd;
	private BigDecimal times;

	private Insurance insurance;


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "age_start")
	public Integer getAgeStart() {
		return this.ageStart;
	}

	public void setAgeStart(Integer ageStart) {
		this.ageStart = ageStart;
	}

	@Column(name = "age_end")
	public Integer getAgeEnd() {
		return this.ageEnd;
	}

	public void setAgeEnd(Integer ageEnd) {
		this.ageEnd = ageEnd;
	}

	@Column(name = "times", precision = 10)
	public BigDecimal getTimes() {
		return this.times;
	}

	public void setTimes(BigDecimal times) {
		this.times = times;
	}
	@ManyToOne(fetch=FetchType.LAZY, cascade = CascadeType.REFRESH,optional = false)
	@JoinColumn(name="insurance_id")
	@JsonIgnore
	public Insurance getInsurance() {
		return insurance;
	}

	public void setInsurance(Insurance insurance) {
		this.insurance = insurance;
	}

}
