package com.hongyu.entity;
// Generated 2017-11-20 20:19:04 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProfitShareStore generated by hbm2java 门店后返
 */
@Entity
@Table(name = "hy_profit_share_store")
public class ProfitShareStore implements java.io.Serializable {

	private Long id;
	private Long storeId;
	private String storeName;
	private Date billingCycleStart;
	private Date billingCycleEnd;
	private BigDecimal amount;
	private Date payDate;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "store_id")
	public Long getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	@Column(name = "store_name")
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "billing_cycle_start", length = 19)
	public Date getBillingCycleStart() {
		return this.billingCycleStart;
	}

	public void setBillingCycleStart(Date billingCycleStart) {
		this.billingCycleStart = billingCycleStart;
	}

	@Column(name = "billing_cycle_end", length = 19)
	public Date getBillingCycleEnd() {
		return this.billingCycleEnd;
	}

	public void setBillingCycleEnd(Date billingCycleEnd) {
		this.billingCycleEnd = billingCycleEnd;
	}

	@Column(name = "amount")
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "pay_date")
	public Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

}
