package com.hongyu.entity;
// Generated 2017-11-20 20:19:04 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfitShareDetail generated by hbm2java
 * (门店、微商)后返详情
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hy_profit_share_detail")
public class ProfitShareDetail implements java.io.Serializable {

	private Long id;
	private String orderCode;
	private Long wechatBusinessId;
	private Long storeId;
	private String productName;
	private Date date;
	private Integer orderSource;
	private BigDecimal settlementPrice;
	private BigDecimal salePrice;
	private BigDecimal profit;
	private Float percentStore;
	private Float percentWechatBusiness;

	

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "order_code")
	public String getOrderCode() {
		return this.orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	@Column(name = "wechat_business_id")
	public Long getWechatBusinessId() {
		return wechatBusinessId;
	}

	public void setWechatBusinessId(Long wechatBusinessId) {
		this.wechatBusinessId = wechatBusinessId;
	}

	@Column(name = "store_id")
	public Long getStoreId() {
		return storeId;
	}

	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "date")
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "order_source")
	public Integer getOrderSource() {
		return this.orderSource;
	}

	public void setOrderSource(Integer orderSource) {
		this.orderSource = orderSource;
	}

	@Column(name = "settlement_price")
	public BigDecimal getSettlementPrice() {
		return this.settlementPrice;
	}

	public void setSettlementPrice(BigDecimal settlementPrice) {
		this.settlementPrice = settlementPrice;
	}

	@Column(name = "sale_price")
	public BigDecimal getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "profit")
	public BigDecimal getProfit() {
		return this.profit;
	}

	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}

	@Column(name = "percent_store")
	public Float getPercentStore() {
		return this.percentStore;
	}

	public void setPercentStore(Float percentStore) {
		this.percentStore = percentStore;
	}

	@Column(name = "percent_wechat_business")
	public Float getPercentWechatBusiness() {
		return this.percentWechatBusiness;
	}

	public void setPercentWechatBusiness(Float percentWechatBusiness) {
		this.percentWechatBusiness = percentWechatBusiness;
	}

}
