package com.hongyu.entity;
// Generated 2017-11-20 20:19:04 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProfitShareWechatBusiness generated by hbm2java
 * 微商后返
 */
@Entity
@Table(name = "hy_profit_share_wechat_business")
public class ProfitShareWechatBusiness implements java.io.Serializable {

	private Long id;
	private Long weChatBusinessId;
	private String wechatBusinessName;
	private String storeName;
	private Date billinyCycleStart;
	private Date billinyCycleEnd;
	private BigDecimal amount;
	private Date payDate;

	

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "wechat_business_id")
	public Long getWeChatBusinessId() {
		return this.weChatBusinessId;
	}

	public void setWeChatBusinessId(Long weChatBusinessId) {
		this.weChatBusinessId = weChatBusinessId;
	}

	@Column(name = "wechat_business_name")
	public String getWechatBusinessName() {
		return this.wechatBusinessName;
	}

	public void setWechatBusinessName(String wechatBusinessName) {
		this.wechatBusinessName = wechatBusinessName;
	}

	@Column(name = "store_name")
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "billiny_cycle_start")
	public Date getBillinyCycleStart() {
		return this.billinyCycleStart;
	}

	public void setBillinyCycleStart(Date billinyCycleStart) {
		this.billinyCycleStart = billinyCycleStart;
	}

	@Column(name = "billiny_cycle_end")
	public Date getBillinyCycleEnd() {
		return this.billinyCycleEnd;
	}

	public void setBillinyCycleEnd(Date billinyCycleEnd) {
		this.billinyCycleEnd = billinyCycleEnd;
	}

	@Column(name = "amount")
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "pay_date")
	public Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

}
