package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * HyQuestionnaireFeedback generated by hbm2java
 */
@Entity
@Table(name = "hy_questionnaire_feedback")
public class QuestionnaireFeedback implements java.io.Serializable {

	private Long id;
	private Date createDate;
	private Date modifyDate;
	private HyAdmin feedbackPerson;
	private String questionnaireSn;
	private Department department;
	private String advice;
	private Date feedbackDate;
	private Integer status;
	private List<QuestionnaireScore> questionnaireScores;
	public QuestionnaireFeedback() {
	}

	public QuestionnaireFeedback(Long id) {
		this.id = id;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "feedback_person")
	public HyAdmin getFeedbackPerson() {
		return this.feedbackPerson;
	}

	public void setFeedbackPerson(HyAdmin feedbackPerson) {
		this.feedbackPerson = feedbackPerson;
	}

	@Column(name = "questionnaire_sn")
	public String getQuestionnaireSn() {
		return this.questionnaireSn;
	}

	public void setQuestionnaireSn(String questionnaireSn) {
		this.questionnaireSn = questionnaireSn;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "department_id")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Column(name = "advice")
	public String getAdvice() {
		return this.advice;
	}

	public void setAdvice(String advice) {
		this.advice = advice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "feedback_date", length = 19)
	public Date getFeedbackDate() {
		return this.feedbackDate;
	}

	public void setFeedbackDate(Date feedbackDate) {
		this.feedbackDate = feedbackDate;
	}
	@Column(name="status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	@OneToMany(fetch=FetchType.LAZY, mappedBy="questionnaireFeedback")
	public List<QuestionnaireScore> getQuestionnaireScores() {
		return questionnaireScores;
	}

	public void setQuestionnaireScores(List<QuestionnaireScore> questionnaireScores) {
		this.questionnaireScores = questionnaireScores;
	}
	@PrePersist
	public void prePersist(){
		this.setCreateDate(new Date());
		this.setStatus(0);//0未填写,1已填写
	}
}
