package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.ibatis.annotations.Many;

/**
 * HyQuestionnaire generated by hbm2java
 */
@Entity
@Table(name = "hy_questionnaire")
public class Questionnaire implements java.io.Serializable {

	private Long id;
	private Date createDate;
	private Date modifyDate;
	private String qusetionnaierSn;
	private String name;
	private Department department;//发起部门
	private HyAdmin operator;//添加人
	private List<QuestionnaireEntry> questionnaireEntries;

	public Questionnaire() {
	}

	public Questionnaire(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "qusetionnaier_sn")
	public String getQusetionnaierSn() {
		return this.qusetionnaierSn;
	}

	public void setQusetionnaierSn(String qusetionnaierSn) {
		this.qusetionnaierSn = qusetionnaierSn;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "department_id")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="operator")
	public HyAdmin getOperator() {
		return operator;
	}

	public void setOperator(HyAdmin operator) {
		this.operator = operator;
	}

	@OneToMany(fetch=FetchType.LAZY,mappedBy="questionnaire",cascade=CascadeType.ALL)
	public List<QuestionnaireEntry> getQuestionnaireEntries() {
		return questionnaireEntries;
	}

	public void setQuestionnaireEntries(List<QuestionnaireEntry> questionnaireEntries) {
		this.questionnaireEntries = questionnaireEntries;
	}
	@PrePersist
	public void prePersist(){
		this.setCreateDate(new Date());
	}
	@PreUpdate
	public void preUpdate(){
		this.setModifyDate(new Date());
	}
}
