package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HyQuestionnaireScore generated by hbm2java
 */
@Entity
@Table(name = "hy_questionnaire_score")
public class QuestionnaireScore implements java.io.Serializable {
	private Long id;
	private QuestionnaireFeedback questionnaireFeedback;
	private QuestionnaireEntry questionnaireEntry;
	private String entry;
	private Department department;
	private Integer score;
	private HyAdmin feedbackPerson;
	
	public QuestionnaireScore() {
	}
	public QuestionnaireScore(Long id){
		this.id=id;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="feedback_id")
	@JsonIgnore
	public QuestionnaireFeedback getQuestionnaireFeedback() {
		return questionnaireFeedback;
	}

	public void setQuestionnaireFeedback(QuestionnaireFeedback questionnaireFeedback) {
		this.questionnaireFeedback = questionnaireFeedback;
	}

//	@Column(name = "feedback_id")
//	public Long getFeedbackId() {
//		return this.feedbackId;
//	}
//
//	public void setFeedbackId(Long feedbackId) {
//		this.feedbackId = feedbackId;
//	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "entry_id")
	public QuestionnaireEntry getQuestionnaireEntry() {
		return this.questionnaireEntry;
	}

	public void setQuestionnaireEntry(QuestionnaireEntry questionnaireEntry) {
		this.questionnaireEntry = questionnaireEntry;
	}

	@Column(name = "score_id")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}
	@Column(name="entry")
	public String getEntry() {
		return entry;
	}

	public void setEntry(String entry) {
		this.entry = entry;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="department")
	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="feedback_person")
	public HyAdmin getFeedbackPerson() {
		return feedbackPerson;
	}

	public void setFeedbackPerson(HyAdmin feedbackPerson) {
		this.feedbackPerson = feedbackPerson;
	}
}
