package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HySignContract generated by hbm2java
 */
@Entity
@Table(name = "hy_sign_contract")
public class SignContract implements java.io.Serializable {

	private Long id;//主键id
	private Date createDate;//创建时间
	private Date modifyDate;//修改时间
	
	private HyAdmin operator;//报名计调
	private String storeName;//使用门店
	private Date startDate;//出团日期

	private HyOrder order;//订单id
	private HyGroup group;//团id
	private Integer contractType;//合同类型, 0国内，1出境，2短线，3单项委托
	private String contractNumber;//合同号
	
	private String referee;//游客代表
	private Integer number;//合同人数
	private String phone;//签约号码
	private Integer status;//签约状态，0待签约，1已签约

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="operator")
	public HyAdmin getOperator() {
		return operator;
	}

	public void setOperator(HyAdmin operator) {
		this.operator = operator;
	}
	@Column(name="store_name")
	public String getStoreName() {
		return storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}
	@Column(name="start_date")
	@Temporal(TemporalType.DATE)
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public HyOrder getOrder() {
		return this.order;
	}

	public void setOrder(HyOrder order) {
		this.order = order;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public HyGroup getGroup() {
		return this.group;
	}

	public void setGroup(HyGroup group) {
		this.group = group;
	}

	@Column(name = "contract_type")
	public Integer getContractType() {
		return this.contractType;
	}

	public void setContractType(Integer contractType) {
		this.contractType = contractType;
	}

	@Column(name = "contract_number")
	public String getContractNumber() {
		return this.contractNumber;
	}

	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}

	@Column(name = "referee")
	public String getReferee() {
		return this.referee;
	}

	public void setReferee(String referee) {
		this.referee = referee;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
