package com.hongyu.entity;
// Generated 2017-12-12 17:05:00 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.hongyu.util.Constants;

/**
 * HyStore generated by hbm2java
 */
@Entity
@Table(name = "hy_store")
@JsonIgnoreProperties({"handler","hibernateLazyInitializer"})
public class Store implements java.io.Serializable {

	private Long id;
	private String storeName;
	private Department department;//门店对应部门
	private Department suoshuDepartment;
//	private Long departmentId;//所属部门id
//	private Long areaId;
	private HyArea hyArea;
	//0待审核,1审核未通过,2审核通过冻结中,3退出待审核,4退出,5激活,6强制激活
	private Integer status;//弃用：0未审核，1未激活，2激活，3强制激活 
	private Integer storeType;//0虹宇门店，1挂靠门店，2直营门店，3非虹宇门店
	private String address;
	private BankList bankList;//门店银行账户信息
	private BigDecimal pledge;
	private Integer pstatus;//0待缴纳，1交纳中，2已缴纳,3退出中
	private Date ppayday;
	private BigDecimal managementFee;
	private Date mpayday;
	private Integer mstatus;//0未填写,1填写中，2待交纳,3缴纳中, 4已缴纳, 5 已过期
	private HyAdmin hyAdmin;//负责人信息
	private Date registerDate;
	private String contract;
	private Date validDate;
	private HyAdmin storeAdder;
//	private String storeAdder;//添加人username
	private String uniqueCode;//统一信用代码
	private String businessLicense;//营业执照
	private String businessCertificate;//经营许可证
	private BigDecimal credits;
	private BigDecimal deposit;
	private String special;//存储强制激活附件地址
	private Integer waibuStoreType;
	//private StoreAccount storeAccount;
	//虹宇门店负责人微商
	private WeBusiness headWebusiness;
	
	public Store() {
	}
	public Store(Long id){
		this.id=id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name="store_name")
	public String getStoreName() {
		return storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}
	@OneToOne(fetch=FetchType.LAZY,cascade=CascadeType.REMOVE)
	@JoinColumn(name="department_id")
	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="suoshudepartment_id")
	public Department getSuoshuDepartment() {
		return suoshuDepartment;
	}
	public void setSuoshuDepartment(Department suoshuDepartment) {
		this.suoshuDepartment = suoshuDepartment;
	}
	//	@Column(name = "suoshudepartment_id")
//	public Long getDepartmentId() {
//		return this.departmentId;
//	}
//
//	public void setDepartmentId(Long departmentId) {
//		this.departmentId = departmentId;
//	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="area_id")
	public HyArea getHyArea() {
		return hyArea;
	}
	public void setHyArea(HyArea hyArea) {
		this.hyArea = hyArea;
	}
//	@Column(name = "area_id")
//	public Long getAreaId() {
//		return this.areaId;
//	}
//
//	public void setAreaId(Long areaId) {
//		this.areaId = areaId;
//	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "type")
	public Integer getStoreType() {
		return this.storeType;
	}

	public void setStoreType(Integer storeType) {
		this.storeType = storeType;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "pledge", precision = 10)
	public BigDecimal getPledge() {
		return this.pledge;
	}

	public void setPledge(BigDecimal pledge) {
		this.pledge = pledge;
	}

	@Column(name = "pstatus")
	public Integer getPstatus() {
		return this.pstatus;
	}

	public void setPstatus(Integer pstatus) {
		this.pstatus = pstatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ppayday", length = 10)
	public Date getPpayday() {
		return this.ppayday;
	}

	public void setPpayday(Date ppayday) {
		this.ppayday = ppayday;
	}

	@Column(name = "management_fee", precision = 10)
	public BigDecimal getManagementFee() {
		return this.managementFee;
	}

	public void setManagementFee(BigDecimal managementFee) {
		this.managementFee = managementFee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mpayday", length = 10)
	public Date getMpayday() {
		return this.mpayday;
	}

	public void setMpayday(Date mpayday) {
		this.mpayday = mpayday;
	}

	@Column(name = "mstatus")
	public Integer getMstatus() {
		return this.mstatus;
	}

	public void setMstatus(Integer mstatus) {
		this.mstatus = mstatus;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "register_date", length = 10)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@Column(name = "contract")
	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_date", length = 10)
	public Date getValidDate() {
		return this.validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="store_adder")
	public HyAdmin getStoreAdder() {
		return this.storeAdder;
	}

	public void setStoreAdder(HyAdmin storeAdder) {
		this.storeAdder = storeAdder;
	}

	@Column(name = "unique_code")
	public String getUniqueCode() {
		return this.uniqueCode;
	}

	public void setUniqueCode(String uniqueCode) {
		this.uniqueCode = uniqueCode;
	}

	@Column(name = "business_license")
	public String getBusinessLicense() {
		return this.businessLicense;
	}

	public void setBusinessLicense(String businessLicense) {
		this.businessLicense = businessLicense;
	}

	@Column(name = "business_certificate")
	public String getBusinessCertificate() {
		return this.businessCertificate;
	}

	public void setBusinessCertificate(String businessCertificate) {
		this.businessCertificate = businessCertificate;
	}

	@Column(name = "credits", precision = 10)
	public BigDecimal getCredits() {
		return this.credits;
	}

	public void setCredits(BigDecimal credits) {
		this.credits = credits;
	}

	@Column(name = "deposit", precision = 10)
	public BigDecimal getDeposit() {
		return this.deposit;
	}

	public void setDeposit(BigDecimal deposit) {
		this.deposit = deposit;
	}

	@Column(name = "special")
	public String getSpecial() {
		return this.special;
	}

	public void setSpecial(String special) {
		this.special = special;
	}

	@Column(name = "waibu_store_type")
	public Integer getWaibuStoreType() {
		return this.waibuStoreType;
	}

	public void setWaibuStoreType(Integer waibuStoreType) {
		this.waibuStoreType = waibuStoreType;
	}


	@ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.REMOVE)
	@JoinColumn(name="bank_id")
	public BankList getBankList() {
		return bankList;
	}

	public void setBankList(BankList bankList) {
		this.bankList = bankList;
	}
	@ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.REMOVE)
	@JoinColumn(name="admin_id")
	public HyAdmin getHyAdmin() {
		return hyAdmin;
	}

	public void setHyAdmin(HyAdmin hyAdmin) {
		this.hyAdmin = hyAdmin;
	}

	@PrePersist
	public void prePersist(){
		this.setRegisterDate(new Date());
		this.setMstatus(0);//0表示未填写,1表示待交纳,2表示已缴纳,3表示已过期
		this.setPstatus(0);//0表示待缴纳，1表示已缴纳,2表示已退回
		this.setDeposit(new BigDecimal("0.00"));
		
	}
	
	@OneToOne(fetch=FetchType.LAZY,cascade=CascadeType.REMOVE)
	@JoinColumn(name="head_webusiness_id")
	@JsonIgnore
	public WeBusiness getHeadWebusiness() {
		return headWebusiness;
	}

	public void setHeadWebusiness(WeBusiness headWebusiness) {
		this.headWebusiness = headWebusiness;
	}
//	@OneToOne(fetch=FetchType.LAZY,cascade=CascadeType.REMOVE)
//	@JoinColumn(name="account")
//	public StoreAccount getStoreAccount() {
//		return storeAccount;
//	}
//	public void setStoreAccount(StoreAccount storeAccount) {
//		this.storeAccount = storeAccount;
//	}
}
