package com.shetuan.controller;

import java.util.HashMap;

import javax.annotation.Resource;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.hongyu.Json;
import com.shetuan.service.HomePageService;
@RestController
@RequestMapping("/openIdConnect/")
public class TestController {

		@RequestMapping(value="token")
		@ResponseBody
		public Json getTotalOrganizationNumber() {
			Json j=new Json();
			HashMap<String,String> m=new HashMap<>();
			m.put("access-token", "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwOUg3NENoekZXc0h0TTdsTnZ6VkJGSS02ZmxSZVRNbzFGbmhKdDhrU0hZIn0");
			m.put("expires_in", "35829");
			m.put("refresh_expires_in", "35829");
			m.put("refresh_token", "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3MTUzYWZhYi0wMDFkLTRlOWMtODM0My04ZTEyYWUzMjRmMjgifQ");
//			access_token: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwOUg3NENoekZXc0h0TTdsTnZ6VkJGSS02ZmxSZVRNbzFGbmhKdDhrU0hZIn0.eyJqdGkiOiIxNTE2ZDA3YS01ZDdlLTQwMDYtOGNmOC1lMDY0ZDc4YjY2MTQiLCJleHAiOjE1Nzc3MjQ2MzQsIm5iZiI6MCwiaWF0IjoxNTc3Njg4ODA1LCJpc3MiOiJodHRwOi8vMTE3LjUwLjU1LjUwOjcwODcvYXV0aC9yZWFsbXMvb2ZpZnRoIiwiYXVkIjoib2ZpZnRoLXdlYiIsInN1YiI6IjA1Nzg2ZTZkLTI4ZDktNDQ0Zi1hYmY2LWM5OTJjZTYyZTVhZCIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9maWZ0aC13ZWIiLCJub25jZSI6IjI4MGRmZDllLTYwOGQtNDRiOS05MmI3LTZjM2UwMWI3M2RhZSIsImF1dGhfdGltZSI6MTU3NzY4ODYzNCwic2Vzc2lvbl9zdGF0ZSI6ImQ3ZWY1YzlhLWQ5ZjQtNGFlMi1iN2U0LWYxZGU1NWRmZDRhNCIsImFjciI6IjAiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InRlYWNoZXIifQ.AWH8nmAIL8rF-J4a2Qh6zT-Izz9sYLMHRUN7MeDShtO9obhNqpQlkMBkMsSx15oxq_YwXzbRlWyIuMwW5GEnfJYgx_aGjJ-PkvFylL0pSoM4iHXd9IJQOdKwE-PIm2WkOIqE1qrFyRwRrTwK6BHVABfaU1jDPejhOdSo5EbagVz9Wnmz3m1gIRk0C7HxrA_BEQRjsFR0IzVyxpO_Bikt-J3ggnE5b6TcTj1psxAuK74wfQZUFe2bljLK9dqIkRjhiWeLzHTGICRl7UkVlg4zVhKHOaZORMIxx8Hma9bwfWhSbHSU3iHRwNJUBmu0qcAGtE1ipHV5TLPJRtUxLYjx2w"
//			expires_in: 35829
//			refresh_expires_in: 35829
//			refresh_token: "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3MTUzYWZhYi0wMDFkLTRlOWMtODM0My04ZTEyYWUzMjRmMjgifQ.eyJqdGkiOiJiYmJkNjFiMS04ZDZhLTQ1ZDUtOTQwYS1hM2FjMjVhNjNjNTEiLCJleHAiOjE1Nzc3MjQ2MzQsIm5iZiI6MCwiaWF0IjoxNTc3Njg4ODA1LCJpc3MiOiJodHRwOi8vMTE3LjUwLjU1LjUwOjcwODcvYXV0aC9yZWFsbXMvb2ZpZnRoIiwiYXVkIjoib2ZpZnRoLXdlYiIsInN1YiI6IjA1Nzg2ZTZkLTI4ZDktNDQ0Zi1hYmY2LWM5OTJjZTYyZTVhZCIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJvZmlmdGgtd2ViIiwibm9uY2UiOiIyODBkZmQ5ZS02MDhkLTQ0YjktOTJiNy02YzNlMDFiNzNkYWUiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJkN2VmNWM5YS1kOWY0LTRhZTItYjdlNC1mMWRlNTVkZmQ0YTQiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJ
			j.setSuccess(true);
			j.setMsg("权限获取成功");
			j.setObj(m);;
			return j;
		}
}
